### ISSUE TITLE
Centos 8 stream repository has been deprecated

### ISSUE THREAD

**Issue by BraisVQ** [opendevstack/ods-quickstarters#1021]
**Describe the bug**
Centos 8 stream repository has been deprecated

**To Reproduce**
1. Build any node agent
2. See error

**Expected behavior**
All agents should properly compile

**Screenshots**
http://[mirror.centos.org/centos/8-stream/readme](http://mirror.centos.org/centos/8-stream/readme)

![image](https://github.com/opendevstack/ods-quickstarters/assets/26645694/813edd5b-7ba1-40fd-9d2d-b0137db4a573)

**Comment by braisvq1996** [comment]
As a temporal workarround, https://vault.centos.org/ will be used as a registry for centos packages as it contains the snapshot from the 31st of May
