### ISSUE TITLE
Maintenance of jdk agent, Java and Spock-Geb quickstarter

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#1032]
**JDK Agent**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| Java | 11, 17 and 21 | N/A | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/jdk/docker/Dockerfile.ubi8#L37-L38) |

**Java-SpringBoot Quickstarter**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| jdk base image | ubi9/openjdk-21  | N/A | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/be-java-springboot/files/docker/Dockerfile#L1) |
| Gradle  | gradle-8.4-bin  | gradle-8.9-bin | [gradle-wrapper.properties](https://github.com/opendevstack/ods-quickstarters/blob/master/be-java-springboot/files/gradle/wrapper/gradle-wrapper.properties#L3) |
| SpringBoot  | 3.2.0  | 3.3.2 | [Jenkinsfile](https://github.com/opendevstack/ods-quickstarters/blob/master/be-java-springboot/Jenkinsfile#L23) |

**Spock-Geb Quickstarter**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| Gradle  | gradle-8.4-bin  | gradle-8.9-bin | [gradle-wrapper.properties](https://github.com/opendevstack/ods-quickstarters/blob/master/be-java-springboot/files/gradle/wrapper/gradle-wrapper.properties#L3) |
| spockVersion | 2.3-groovy-4.0  | N/A | [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |
| Junit  | 5.10.1 | 5.10.1| [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |
| Geb  | 7.0 | N/A | [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |
| Selenium | 4.15.0| 4.23.0 | [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |
| htmlunit  | 4.13.0 | N/A | [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |
| unirest  | 3.14.5 | N/A | [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |

The Spock-Geb Quickstarter maintenance can be part of #1025

@garcanam @bassagan

**Comment by renedupont** [comment]
@braisvq1996 Is there a reason to keep java 11? the support for it ended last year september. Is there anything that relies on that? I think you updated the cnes report to a version that does not require java 11 anymore, right? We could instead include java 21 as this is a LTS version as well.

**Comment by braisvq1996** [comment]
The current SonarQube version (9.9) still requires java 11.
From Sonarqube 10.x, the scanner can be triggered using java 17

My intention is for this to be the last revision to have java 11 because Java 11 will also end its support in Jenkins soon -> https://github.com/opendevstack/ods-core/issues/1295

**Comment by stitakis** [comment]
For the sake of forsting innovation and using the latest java features I would also include the latest LTS java version and also intermediary which is today version 22, but we can opt for version 23 once is released in september.

**Comment by renedupont** [comment]
@stitakis The latest LTS (21) is in the agent by now: https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/jdk/docker/Dockerfile.ubi8#L39

**Comment by braisvq1996** [comment]
With the changes on the [next Jenkins update,](https://github.com/opendevstack/ods-core/pull/1299) java 11 gets removed so only jdk agent will maintain java 11 for now

**Comment by renedupont** [comment]
I'm confused I think. Wouldn't that mean that the sonar scanner would not work anymore for any jenkins agent other than JDK agent because according to your comment above it requires Java 11?

**Comment by braisvq1996** [comment]
My bad @renedupont, what I mean to say is that the current binary for the SonarQube scanner needs java 11 but I intend to update that so we can use java 17. This change will apply to all agents, no only jdk.

I still need to test this to be sure it works properly, but if everything goes well java 17 will be the default java version from now on and we will maintain java 11 on jdk agent for retrocompatibility.

![image](https://github.com/user-attachments/assets/26293816-da59-4dbd-ba94-74534f3173aa)
