### ISSUE TITLE
jenkins agent jdk - build failure

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-quickstarters#1037]
**Describe the bug**
Jenkins Agent JDK builds fail within PRs:

Dockerfile.ubi8:36
--------------------
  35 |     # Note: use java scripts are executed to test the scripts but also use-j11.sh in called 3nd place to set is as default version
  36 | >>> RUN yum -y --nobest --skip-broken update && \
  37 | >>>     yum install -y java-11-openjdk-devel && \
  38 | >>>     yum install -y --enablerepo Adoptium temurin-17-jdk && \
  39 | >>>     yum install -y --enablerepo Adoptium temurin-21-jdk && \
  40 | >>>     yum install -y binutils && \
  41 | >>>     yum updateinfo -y && \
  42 | >>>     yum repolist -y && \
  43 | >>>     sh -c "yum list installed | grep -i '\(java\|jdk\|temurin\)'" && \
  44 | >>>     yum clean all -y && rm -rf /var/cache/yum
  45 |     
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c yum -y --nobest --skip-broken update &&     yum install -y java-11-openjdk-devel &&     yum install -y --enablerepo Adoptium temurin-17-jdk &&     yum install -y --enablerepo Adoptium temurin-21-jdk &&     yum install -y binutils &&     yum updateinfo -y &&     yum repolist -y &&     sh -c \"yum list installed | grep -i '\\(java\\|jdk\\|temurin\\)'\" &&     yum clean all -y && rm -rf /var/cache/yum" did not complete successfully: exit code: 1
Error: Process completed with exit code 1.

**Comment by braisvq1996** [comment]
JDK agent is prone to failure due to the instability of adoptium repositories for jdk.....

![image](https://github.com/user-attachments/assets/5431624b-6741-4e15-83a4-0aa541efe46b)
