### ISSUE TITLE
springboot: update archiveName property in gradle.build

### ISSUE THREAD

**Issue by renedupont** [opendevstack/ods-quickstarters#104]
Since gradle version 5.4.1 there are some deprecated properties (https://docs.gradle.org/5.4.1/dsl/org.gradle.api.tasks.bundling.Jar.html). One of them is archiveName which is used in the quickstarter template and will most likely be removed in gradle 7.

For example: 
```
bootJar {
    archiveName "app.jar"
    destinationDir file("$buildDir/../docker")
}
```
needs to look like this:
```
bootJar {
    archiveFileName = "app.jar"
    destinationDirectory = file("$buildDir/../docker")
}
```

I am not sure which gradle version is being used, maybe this needs to be updated too?

**Comment by clemensutschig** [comment]
@stitakis  - on your plate?
