### ISSUE TITLE
Rshiny oauth_proxy has websocket timeout

### ISSUE THREAD

**Issue by FlorianASchroeder** [opendevstack/ods-quickstarters#106]
**Describe the bug**
When using R Shiny via oauth_proxy the browser session disconnects after 4 minutes being idle. The only way to recover is by reloading the page, losing all session state.
It seems that the oauth-proxy introduces a websocket timeout which kills the Shiny session.

If instead connecting to the Shiny Dashboard via `oc port-forward <shiny_pod> <port>` and `http://localhost:<port>`, by-passing the oauth_proxy, then the connection stays alive indefinitely (> 2h).

**To Reproduce**
1. Provision new R Shiny app, wait for deployment.
2. Access the URL and authenticate
3. Wait until the default Dashboard greys out (should take around 5 minutes) which indicates that the websocket got closed.

**Expected behavior**
The Shiny session should never timeout.

**Screenshots**
"healthy" websocket as seen in Chrome DevTools -> Network:
![image](https://user-images.githubusercontent.com/8073101/72166526-b2d57c80-33c9-11ea-960e-bc713237853f.png)
"healthy" Dashboard:  
![image](https://user-images.githubusercontent.com/8073101/72166454-8faacd00-33c9-11ea-878f-d063d1573a98.png)

After timeout:  
DevTools:
![image](https://user-images.githubusercontent.com/8073101/72167014-a43b9500-33ca-11ea-92c9-43e7990256d8.png)
Dashboard:  
![image](https://user-images.githubusercontent.com/8073101/72166996-98e86980-33ca-11ea-88ea-68bda32e5693.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack: 1.2.x
 - OpenShift oauth-proxy: 2.3.0

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
There are no logs..

**Additional context**
This is potentially related to:  
https://github.com/openshift/oauth-proxy/blob/098bda57d53b72db2f8333201041327bb1134c63/http.go#L123

**Comment by michaelsauter** [comment]
FYI @gerardcl 

@FlorianASchroeder Did you check whether there is a way to configure `oauth-proxy` differently?

**Comment by FlorianASchroeder** [comment]
yes I have checked here https://github.com/openshift/oauth-proxy/#command-line-options  but couldn't find any appropriate options..

**Comment by FlorianASchroeder** [comment]
I managed to increase the timeout to 1h by digging into oauth-proxy:  
![image](https://user-images.githubusercontent.com/8073101/72435651-dd934c80-379e-11ea-9400-1b2fc9d5b4fc.png)
But the code is currently in my own fork: https://github.com/FlorianASchroeder/oauth-proxy/tree/fix/websocket-timeout

**Comment by michaelsauter** [comment]
@FlorianASchroeder Nice work! Have you opened an issue at `oauth-proxy` yet, maybe with a reference to your code? This sounds like sth. that could be accepted upstream ...

**Comment by gerardcl** [comment]
Hi @FlorianASchroeder , I have been debugging a little and for me in three different clusters the timeout is ~30, could you test it again please?

**Comment by FlorianASchroeder** [comment]
Hi @gerardcl, I deployed a fresh quickstarter with ODS 2.0 and still got a timeout after about 5 minutes in Chrome v80 and Opera v66:
![image](https://user-images.githubusercontent.com/8073101/74344022-42e15a00-4dac-11ea-9d0f-a27b1126bc9c.png)

On Edge v44 and IE 11.973.x there seems to be no issue with the timeout.

**Comment by clemensutschig** [comment]
@FlorianASchroeder  - works, @gerardcl  - can you follow up?

**Comment by gerardcl** [comment]
Hi! it seems this is behaving different depending on the use case and the browser. @FlorianASchroeder shall we consider this as a non-issue if we expect users of the app to keep it using (so not timout happens while using it) and if not they close it? I guess the issue came up because you are here a developer but not a user of the provided dashboard, right?

**Comment by FlorianASchroeder** [comment]
It's up to you whether you want to use the fixed image or keep the official one. You can store this info as a workaround in case someone else is negatively affected by the timeout in the future.

**Comment by gerardcl** [comment]
We close this issue since the expected use case is not suffering from it, we will reopen it if it comes back.
