### ISSUE TITLE
 fe-react quickstarter provisioning fails

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#117]
**Describe the bug**
fe-react component provisioning fails when `npm init react-app fe-react`

**To Reproduce**
1. In ODS 2.x/master, go to provisioning app and provision fe-react component
2. Jenkins provisioning stage `generate fe-react` fails

**Expected behavior**
 The component should be provisioned without issues

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack: master, 2.x (might be any version)

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```bash
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (generate fe-react)
[Pipeline] sh
[newproject-cd-ods-quickstarter-fe-react-fe-react-2x] Running shell script
+ npm init react-app fe-react
npx: installed 91 in 8.078s

The directory fe-react contains files that could conflict:

  Jenkinsfile
  Jenkinsfile.template
  files
  ocp.env
  sonar-project.properties.template

Either try using a new directory name, or remove the files listed above.
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

**Additional context**
We need to update the jenkinsfile to assure no existing-file issues are found.

**Comment by clemensutschig** [comment]
looks like its in the wrong directry?! .... there should never by file conflicts ...

**Comment by gerardcl** [comment]
right, @cschweikert found out the issue is related to latest changes related to `quickstarterBasepath` and `componentId` too

**Comment by michaelsauter** [comment]
@cschweikert Thanks for figuring this one out!

I am going to close this issue as it is not a per-quickstarter problem but a more general one. We need to prevent the problem in the prov-app. Additionally, we can add a safeguard in the pipeline, but in order to give feedback we need more name validation in the prov app.
