### ISSUE TITLE
fe-angular quickstarter provisioning fails

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#118]
**Describe the bug**
fe-angular component provisioning fails when `ng new fe-angular --style=scss --skip-git --skip-install`

**To Reproduce**
1. In ODS 2.x/master, go to provisioning app and provision fe-angular component
2. Jenkins provisioning stage `init Project` fails

**Expected behavior**
 The component should be provisioned without issues

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack: master, 2.x (might be any version)

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```bash
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (init Project)
[Pipeline] sh
[newproject-cd-ods-quickstarter-fe-angular-fe-angular-2x] Running shell script
+ sh fe-angular/init.sh --project newproject --component fe-angular --group com.bix-digital.newproject
+++ dirname fe-angular/init.sh
++ cd fe-angular
++ pwd
+ SCRIPT_DIR=/tmp/workspace/newproject-cd/newproject-cd-ods-quickstarter-fe-angular-fe-angular-2x/fe-angular
+ [[ 6 > 0 ]]
+ case $1 in
+ PROJECT=newproject
+ shift
+ shift
+ [[ 4 > 0 ]]
+ case $1 in
+ COMPONENT=fe-angular
+ shift
+ shift
+ [[ 2 > 0 ]]
+ case $1 in
+ GROUP=com.bix-digital.newproject
+ shift
+ shift
+ [[ 0 > 0 ]]
+ echo 'generate project'
generate project
+ ng new fe-angular --style=scss --skip-git --skip-install
ERROR! fe-angular/README.md already exists.
The Schematic workflow failed. See above.
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

**Additional context**
Fix in the provisioning jenkinsfile is required --> check README.md file.

**Comment by michaelsauter** [comment]
I am going to close this issue as it is not a per-quickstarter problem but a more general one. We need to prevent the problem in the prov-app. Additionally, we can add a safeguard in the pipeline, but in order to give feedback we need more name validation in the prov app.
