### ISSUE TITLE
ds-ml-service quickstarter provisioning fails

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#119]
**Describe the bug**
ds-ml-service component provisioning fails when `cp -v ds-ml-service/README.md ds-ml-service`

**To Reproduce**
1. In ODS 2.x/master, go to provisioning app and provision ds-ml-service component
2. Jenkins provisioning stage `copy files from quickstart to generated project` fails

**Expected behavior**
 The component should be provisioned without issues

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack: master, 2.x (might be any version)

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```bash
[Pipeline] sh
[newproject-cd-ods-quickstarter-ds-ml-service-ds-ml-service-2x] Running shell script
+ cp -v ds-ml-service/README.md ds-ml-service
cp: 'ds-ml-service/README.md' and 'ds-ml-service/README.md' are the same file
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

**Additional context**
Fix in the provisioning jenkinsfile is required --> check README.md file

**Comment by michaelsauter** [comment]
I am going to close this issue as it is not a per-quickstarter problem but a more general one. We need to prevent the problem in the prov-app. Additionally, we can add a safeguard in the pipeline (which is what the associated PR achieves), but in order to give feedback we need more name validation in the prov app.
