### ISSUE TITLE
Discussion: Support of quotas

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-quickstarters#13]
Currently, we only support memory quotas.
For stability reasons, it would make sense to impose some quotas on the openshift side also on CPU and storage usage.

But if these quotas are enabled on the OpenShift cluster, every DC [must specify its requests and limits](https://docs.openshift.com/container-platform/3.11/dev_guide/deployments/basic_deployment_operations.html#deployment-resources)

To support quotas on an OpenShift cluster, we must therefore specify these quotas, otherwise deployments based on our quickstarters fail on clusters that specify quotas.

A starting point would be (as with the memory quota) to specify the same values in the component creation templates for all [types of quickstarters](https://github.com/opendevstack/ods-project-quickstarters/blob/064e35a7e4fb7d957f72bdf5a4ea606e6e56ebef/ocp-templates/templates/component-environment.yml#L93).

And document in the OpenDevStack documentation how to change requests and limits.

**Comment by michaelsauter** [comment]
Replacing this with the more specific #74.
