### ISSUE TITLE
Add health endpoint to Go quickstarter

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#137]
Healthchecks should be configured out of the box, therefore the Go quickstarter should have a health endpoint.

Related to https://github.com/opendevstack/ods-quickstarters/issues/11.

**Comment by michaelsauter** [comment]
@henrjk What do you think? Move to v4?

**Comment by henrjk** [comment]
Looks like one would need to get the readiness probe configured somewhere in here:

https://github.com/opendevstack/ods-quickstarters/blob/8a04405332decb0464787278600f2dc201452727/common/ocp-config/component-environment/component-template.yml#L125

@michaelsauter do you see a good way to do this is only for golang?
If not I think we should move it to v4 as well.

**Comment by michaelsauter** [comment]
I would have created a separate template, and then move all quickstarters to it over time.

Further, each quickstarter would need to add en endpoint that can be checked for health (this can also be an existing one but I'd be careful with logging).

For me, doing this just for Go is not that helpful - it would be nice if every quickstarter was setup this way. However, that is not going to happen for v3, so that's why I thought we might as well move it to v4. Maybe then we can move all, so we don't have any duplication in templates ...

**Comment by henrjk** [comment]
Let's do it for v4 then
