### ISSUE TITLE
Configure Jenkinsfile Templates to use Global Library Annotation

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-quickstarters#150]
**Is your feature request related to a problem? Please describe.**
Shared library isn't resolved as global during compilation of Jenkinsfile. So any static method usage in the shared library results in failed pipeline and manual script approvals. 

**Describe the solution you'd like**
Annotate the shared library in the Jenkinsfile templates so that its interpreted as a Global Library. This will let the Jenkinsfile reference any static method that stem from the ods-jenkins-shared-library.

**Comment by sino92** [comment]
This issue is resolved from BI X side. However I'll keep this open until the changes are released.

**Comment by clemensutschig** [comment]
this is fixed in 2.x and master 
e.g in https://github.com/opendevstack/ods-quickstarters/blob/master/be-golang-plain/Jenkinsfile.template
