### ISSUE TITLE
Lack of automation to test changes in quickstarters

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-quickstarters#151]
**Is your feature request related to a problem? Please describe.**
I was testing my changes in one of the quickstarters. I was able to mock the provisioning of a component using [this](https://github.com/opendevstack/ods-quickstarters/wiki/Run-quickstarter-via-Jenkins) page thanks to @michaelsauter. 

**Describe the solution you'd like**
Automate the steps explained there with scripts to save people time to test.

**Comment by michaelsauter** [comment]
FYI I had the idea that this could potentially be an interactive script that prompts for the necessary input one after the other, explaining at every step how the parameter is used for.

I have had several conversations now with people using that script and they were all unsure what to input and which effect that would have.

**Comment by sino92** [comment]
Closing this issue as what we need for now is already here: https://github.com/BIX-Digital/ods-contrib/tree/master/quickstart-with-jenkins
