### ISSUE TITLE
Angular quickstarter does not have enabled the stage for scan for sonarqube

### ISSUE THREAD

**Issue by borja44** [opendevstack/ods-quickstarters#166]
**Describe the bug**
fe-angular component provisioning does not have enabled the stage for /*
   stageScanForSonarqube(context)

**To Reproduce**

After checking the all stages, there is no sonarqube stage on the jenkinsfile

**Affected version (please complete the following information):**

https://github.com/opendevstack/ods-quickstarters/blob/2.x/fe-angular/Jenkinsfile.template#L29-L33

**Comment by stitakis** [comment]
@borja44 we have enabled the sonarqube stage per default for the Angular quickstarter in `2.x` and `master` branch. These are the corresponding merged PRs #172 and #173

**Comment by borja44** [comment]
@stitakis have you tried? I've tried same on a repo on friday afternoon and didn't work

**Comment by clemensutschig** [comment]
@borja44  - this is fixed in 2.0 and master 
https://github.com/opendevstack/ods-quickstarters/blob/2.x/fe-angular/Jenkinsfile.template#L23-L24

ok to close?

**Comment by clemensutschig** [comment]
fixed in master as well
