### ISSUE TITLE
Rebuild jenkins slave images if new slave base image is pushed

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#17]
it would be great that if a new build of the Jenkins slave base image is happening then its child images (slave images) are triggered to be rebuild again too.

solution could be to add the "from" statement in their BC: https://docs.okd.io/latest/rest_api/apis-build.openshift.io/v1.BuildConfig.html

**Comment by gerardcl** [comment]
hi @michaelsauter , do we really want this yet? I would say no since we are indeed also removing triggers when rolling out new ODS versions and managing it via Makefile in ods-core, right?

if yes, then we can close this ticket! 👍

**Comment by michaelsauter** [comment]
I think also @hugowschneider was against this because it hindered testing. I would say having no triggers is fine, and rebuild etc. should be an explicit action (even if triggered automatically ...)

Closing for now.
