### ISSUE TITLE
Angular / Node Builds are not distinguishing between DEV and PROD Environment

### ISSUE THREAD

**Issue by ManuelFeller** [opendevstack/ods-quickstarters#18]
Currently there are no environment dependent builds.
This prevents Angular Applications form being build with the `--prod` parameter, but might also affect other Quickstarters / Frameworks.

The first affected place I would suggest to make environment aware is
https://github.com/opendevstack/ods-project-quickstarters/blob/4446edf4a8929474035f781d91e99a771f20ac8e/boilerplates/fe-angular/Jenkinsfile#L38

There adding another type of build call e.g. `yarn buildprod` in case of a release environment could help.
That then needs to be added to the according `package.json` of a project.
So it might have to be added to all the Quickstarters but would enable ODS to have environment specific configurations in the frontend, e.g. different tracking id's for development and production.

It needs to be evaluated what configuration option makes sense (use it or not, what branch type / name is seen as production, ...)

**Comment by michaelsauter** [comment]
@ManuelFeller Could you add the suggestion by @SHoen to the `Jenkinsfile.template`? I think that would be a good improvement for 3.x.

**Comment by ManuelFeller** [comment]
@michaelsauter Will do, sure

**Comment by ManuelFeller** [comment]
@SHoen since by default we only have `master` and `develop` (no `prod`) branches I only check for master in my PR. Also, for being consistent, I used `'master'.equals(context.gitBranch)` as it was already done in the Ionic Quickstarter.
Still thanks for reminding me with your suggestion that I opened this quite some time ago ;-)
