### ISSUE TITLE
Docker MAINTAINER is deprecated

### ISSUE THREAD

**Issue by oalyman** [opendevstack/ods-quickstarters#19]
The MAINTAINER instruction in docker files is deprecated in favour of LABEL.

see: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

**Comment by metmajer** [comment]
I see the need to have core maintainers determined for each quickstarter, especially as we see quickstarters increasingly being used in enterprise environments. By having the core maintainers identified...

1) author(s) of a quickstarter come to realize that there is an ownership attached to their work
2) users of a quickstarter know who are the people behind it and can provide best support in the community

FYI @clemensutschig @michaelsauter

**Comment by michaelsauter** [comment]
@metmajer I totally agree, and will try to tackle this starting this week. I'll add an update here.

**Comment by clemensutschig** [comment]
@michaelsauter  - done?

**Comment by michaelsauter** [comment]
Hmm, I think we can close this one. The "owner" of a quickstarter doesn't map exactly to a Dockerfile, so instead I suggest https://github.com/opendevstack/ods-quickstarters/issues/398.
