### ISSUE TITLE
Provisioning a release manager should not redeploy Jenkins

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#206]
When a release manager component is provisioning, the Jenkins Pipeline triggers a redeploy of its master: https://github.com/opendevstack/ods-quickstarters/blob/master/release-manager/create-ocp-resources.sh#L21.

This is very surprising and potentially broken / dangerous. We should not do this. We need to find another way to have the information present without a restart.

**Comment by clemensutschig** [comment]
@michaelsauter  - this is even worse .. because that means that the provision job could die itself

**Comment by clemensutschig** [comment]
@gerardcl @michaelsauter   - my proposal would be .. to disable the config change trigger - do all the stuff and enable it .. thoughts .. that thing we should fix quickly ... seriously

**Comment by michaelsauter** [comment]
My thoughts on this:

I believe it to be fundamentally wrong to trigger a redeployment of Jenkins from within Jenkins. No matter where you do it. I would like us to find a way around doing this. Given that it is one single environment variable that we set, I am inclined to just default the value when we read it in a pipeline. To have it flexible, we could allow a user to set an environment variable to override. 

The other option, which I'd also be open to, would be to set this value from the beginning (this would have the drawback of "breaking" old projects - but we could combine it with the previous approach as well).
