### ISSUE TITLE
Update Ionic quickstarter to newest Angular version

### ISSUE THREAD

**Issue by cschweikert** [opendevstack/ods-quickstarters#21]
Ionic quickstarter still uses Angular 5. It should be updated to use at least version 8 like in fe-angular, if possible.

This update should also include the improvements of SonarQube support, which were introduced on fe-angular. See also https://github.com/opendevstack/ods-project-quickstarters/issues/212

**Comment by bljubisic** [comment]
As a first step I would like to recommend to modify fe-ionic quickstarter to follow the same principle as fe-angular quickstarter. After that we can modify the quickstarter to use latest ionic update.
