### ISSUE TITLE
Quickstarters need to generate code coverage (and report to SQ)

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#213]
**Describe the bug**
Quickstarters lack consistent code coverage reporting, some have (jacoco) others don't. 

This is a must fix for ODS 3

This is a follow up from #175 

exit criteria: all qs of type ods / ods-test have the right code coverage show  up in SQ

**Comment by michaelsauter** [comment]
Status:

- [ ] airflow-cluster
- [x] ~be-fe-mono-repo-plain~
- [ ] be-gateway-nginx
- [x] be-golang-plain
- [x] be-java-springboot
- [ ] be-python-flask
- [ ] be-scala-play
- [ ] be-typescript-express
- [x] ~docker-plain~
- [ ] ds-jupyter-notebook
- [ ] ds-ml-service
- [ ] ds-rshiny
- [ ] e2e-cypress
- [ ] e2e-spock-geb
- [ ] fe-angular
- [ ] fe-ionic
- [ ] ods-document-gen-svc
- [ ] ods-provisioning-app
- [x] ~release-manager~

QS with no owners / about to be removed:
- [ ] be-scala-akka
- [ ] fe-react
- [ ] fe-vue

**Comment by gerardcl** [comment]
-for `ds-jupyter-notebook` and `ds-rshiny` I think they do not require it based on the type of service they are
-for `airflow-cluster` we are in conversations to move it to extra-quickstarters
-regarding `be-python-flask`and `ds-ml-service`: AFAIK I already implemented that, isn't it working anymore?

**Comment by michaelsauter** [comment]
@gerardcl I simply did not look into Python / ML. Updated the list now, thanks for the comments!

**Comment by bljubisic** [comment]
For fe-ionic there is a branch Fix-Ionic-Unit-Test-Reporting which is a fix for Ionic.

**Comment by michaelsauter** [comment]
Closing this as all quickstarters have code coverage configured now!
