### ISSUE TITLE
R-Studio quickstarter

### ISSUE THREAD

**Issue by alanbort** [opendevstack/ods-quickstarters#23]
This is an evolution on the R-Shiny quickstarter. The real use case we get from users starts from R-Studio where they do some interactive coding and only once they complete profiling and exploration do they move to visualization on R-Shiny. The current quickstarter provides R-Shiny, but developing the app is left out. 

The proposed solution is to implement an R-Studio Server quickstarter with the ability to launch R-Shiny servers for testing/evaluation.

**Comment by gerardcl** [comment]
hi @alanbort  I believe we can close this ticket since there is no expectation to run R-Studio within OpenShift, right?

**Comment by gerardcl** [comment]
closing this
