### ISSUE TITLE
Add gcc/g++ to support builds with CGO_ENABLED=1

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-quickstarters#230]
**Describe the bug**
Golang builds can either yield a static, fully self-contained binary, or be dynamically-linked against a C library. Currently, when building the latter using `CGO_ENABLED=1`, the build fails because of a missing `gcc`.

**To Reproduce**
`CGO_ENABLED=1 go build`

**Expected behavior**
The build succeeds.

**Affected version (please complete the following information):**
 - OpenShift: [e.g. 3.9, 3.11]
 - OpenDevStack 2.x

**Proposed solution**
Add `gcc` and `gcc-c++` into the Golang build slave. The presence of both further allows developers to import C/C++ files into Golang. For this to work, in the Dockerfile, add:

```
RUN yum install -y gcc gcc-c++
```

**Comment by metmajer** [comment]
The correct behavior has been verified on a custom slave.

**Comment by clemensutschig** [comment]
Put into Slave?

**Comment by metmajer** [comment]
@clemensutschig correct!
