### ISSUE TITLE
Make ds-ml-quickstarter work with mono-repo MRO implementation

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#231]
follow up from opendevstack/ods-jenkins-shared-library#242 and opendevstack/ods-mro-jenkins-shared-library#188

**Is your feature request related to a problem? Please describe.**
1. use the new stages :) to remove all the clutter, that is now standard 
1. for ds-ml quickstarter to work with the MRO - the labels of all components - that need promotion - have to use the standard pattern `app: '${PROJECT}-${COMPONENT}'` 

as of now the quickstarter sets the component to be `${COMPONENT}`-training/prediction-service, which tailor does not know if in the MRO context (it searches for `${COMPONENT}` being the repo.id.

Second thought: we have to talk about what promote to production means ....
assuming you'd call the component environment on the first attempt - as is -> without `-training..` for the prediction service we would pick only that one up - and transport ..

BUT this highly depends on if you want to retrain on Q and P ... 

NB: I tested the mro with the standard `app` selector, and this works now

**Comment by gerardcl** [comment]
So basically with the required change we will also get a better deployment picture since both services will be under the same app name.
@sklingel @hugowschneider you will love it

**Comment by clemensutschig** [comment]
@gerardcl see : https://github.com/opendevstack/ods-quickstarters/pull/233/files
