### ISSUE TITLE
airflow qs not transportable to Prod (on other cluster)

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#238]
airflow QS relies on images in `*-cd` - mro only picks up images in the source namespace `dev` and in the protected `openshift` namespace. per design. 

In order to make this work, the QS needs to have a image stream with the image tagged into in `dev`.

The reason is pretty simple - we `tailor export` only imagestreams in the `dev` project - and those will be imported, and the DC's image pointers rewritten to th target project

**Comment by gerardcl** [comment]
since we have moved `airflow-cluster` to `extra-quickstarters` repo we do not see a need for having it fully integrated, can we close this ticket then?

see updated list here https://github.com/opendevstack/PMC/wiki/ODS-3.0-Quickstarters

**Comment by michaelsauter** [comment]
Given airflow is going to be removed, I'm taking this off ODS 3.0.

**Comment by metmajer** [comment]
@michaelsauter needed for BRASS

**Comment by clemensutschig** [comment]
@metmajer - This One is really hard to solve.. as the Images sit in the project-cd namespace... @hugowschneider @gerardcl - what would promote to production mean for airflow?

**Comment by hugowschneider** [comment]
Airflow only depends on shared base images, the images could be in any shared project space. But I guess this should not be a concern anymore since Airflow will be moved out of the Quickstarter. 

In regards to the projects using it, we had an agreement for moving the Airflow quickstarter out of the "supported/official" repo.

**Comment by metmajer** [comment]
@hugowschneider again, we want to onboard BRASS, which requires the presence of Airflow in D/Q/P. If you put it into the unsupported repo, it means they'll need to stick with the latest supported one. Help on how to properly configure it to make it work will be needed.

**Comment by hugowschneider** [comment]
@metmajer That was not our understanding from the email thread we had and my guess is that @gerardcl is already moving it out.

**Comment by metmajer** [comment]
@hugowschneider @gerardcl then we need to rediscuss. thanks

**Comment by michaelsauter** [comment]
I see it like this:

* The QS is not maintained, so it is not part of 3.0 officially. This was discussed and agreed upon.
* BRASS has a component which was originally created using this QS (ODS v1.2 I think). Back then, the QS did not support "move to production", and did not promise to do so either. There is nothing we take away from BRASS by moving this QS out of ODS 3.0
* For BRASS, we need to sit down internally (@hugowschneider @gerardcl @metmajer) and figure out how we can help them to move their component to production. However, this has - in my eyes - nothing to do with the GitHub codebase here.

Thoughts?

**Comment by hugowschneider** [comment]
Agreed

**Comment by michaelsauter** [comment]
BTW: The simplest thing for BRASS, I believe, is to just move the images to `brass-dev`. Keeping the images in `brass-cd` was done to avoid having to rebuild from scratch in dev and test. This concern is irrelevant for the orchestration pipeline has we promote images from dev to test to prod anyway.

**Comment by metmajer** [comment]
@michaelsauter I assume to have an incomplete understanding of the current limitations. If there's a way for BRASS to move their entire application to P somehow, then fine with me. The point is that we're focusing our people on BRASS' success and I wouldn't like to see this QS blocking this. Having a conversation over the limitations is much appreciated. Cheers @michaelsauter @hugowschneider @gerardcl

**Comment by michaelsauter** [comment]
@metmajer The point I'm trying to make is that any changes to the QS on GitHub are irrelevant for BRASS. A quickstarter is only used once to create the initial skeleton for a component. From this point forward, there is no connection between the quickstarter and the component. Changes in either part do not affect the other ...

**Comment by gerardcl** [comment]
we are closing this ticket since airflow-cluster has already been moved after required agreements to extra-quickstarters

**Comment by metmajer** [comment]
@gerardcl you have moved the stuff a day ago, this ticket is way older. BRASS needs to fly.

**Comment by gerardcl** [comment]
sure @metmajer !  as per agreement let's tackle it internally, or do you want to keep it open in order to provide such fix already within ODS 2.x? I would suggest, since BRASS is not 100% implementing this QS skeleton, to tackle it internally.

**Comment by metmajer** [comment]
Great, let’s handle it internally then. Cheers, @gerardcl!
