### ISSUE TITLE
Jupyter -> JupyterHub Quickstarter

### ISSUE THREAD

**Issue by alanbort** [opendevstack/ods-quickstarters#24]
The current Jupyter quickstarter provides a single user notebook. This poses a challenge where multiple team members want to use the tool and if sensitive information is required (e.g. passwords) they are visible to the entire project team.

The proposed solution is to implement JupyterHub, which has native user serparation and authentication/authorization integration options with PAM, OAUTH and LDAP.

**Comment by gerardcl** [comment]
hi @alanbort  I believe we can close this ticket since there is no expectation to run Jupyter Hub within OpenShift, right?

**Comment by gerardcl** [comment]
closing it
