### ISSUE TITLE
(bug): links are broken to documentation

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-quickstarters#246]
**Describe the bug**
Links to the documentation including `/latest/` in the url are broken

**To Reproduce**
1. Go to [README.md](https://github.com/opendevstack/ods-quickstarters/blob/master/README.md)
2. Click on `See **OpenDevStack Quickstarters** for details.`
4. See `Page Not Found` error

**Expected behavior**
Working links

**Screenshots**
N/A

**Affected version (please complete the following information):**
N/A

**Comment by michaelsauter** [comment]
The issue here is that the documentation always pointed to `latest`, and that isn't a good default as it is a moving target. Also, there was no way to update the documentation while keeping the old links. Painfiul, but no progress without it. I'll update the links in the source code.

**Comment by SimonGolms** [comment]
@michaelsauter as written in the `To Reproduce` step, the links in the `README.md` to the ods documentation are effected and do not work.
https://github.com/opendevstack/ods-quickstarters/blob/68bd1718139c12b4c977ba7da4da045a8d4c4cca/README.md#L9-L16

**Comment by SimonGolms** [comment]
PR #257 created

**Comment by michaelsauter** [comment]
Sorry, misread it and fixed it for the shared library. Opened PR https://github.com/opendevstack/ods-quickstarters/pull/259 which should fix it for the quickstarters.
