### ISSUE TITLE
MRO integration - metadata yml for quickstarter should define component's type, not release manager's metadata

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#247]
today MRO logic (and release manager's `metadata.yml` define for each component (instance) which type it is .. `ods`, `ods-test` or `ods-service` .. 

Reference(s):
1. set if not defined: https://github.com/opendevstack/ods-mro-jenkins-shared-library/blob/master/src/org/ods/util/Project.groovy#L939-L942

1. use: https://github.com/opendevstack/ods-mro-jenkins-shared-library/blob/master/src/org/ods/util/MROPipelineUtil.groovy#L510

Why are we not predefining them in the metadata.yml of a component, this way we have control at quickstarter level?

@metmajer

**Comment by clemensutschig** [comment]
based on opendevstack/ods-mro-jenkins-shared-library#195

**Comment by metmajer** [comment]
Fully agreed @clemensutschig, that's the way it should be. We had initially chosen to do it the way it is now to avoid touching the quickstarters if I remember correctly. Anyway, care will need to be taken all type queries will need to be adjusted.
