### ISSUE TITLE
Add Oracle XE Quickstarter 

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-quickstarters#25]
Create a quickstarter that provides a oracle xe dbms project.

**Comment by michaelsauter** [comment]
@stefanlack In ODS 2, one can point to private quickstarters. I would regard Oracle XE as a case for that. Agreed?

**Comment by stefanlack** [comment]
@michaelsauter in my opinion this can be a private quickstarter.

**Comment by michaelsauter** [comment]
Perfect, then I'll close this.
