### ISSUE TITLE
be-golang-plain fails go-junit-report: command not found

### ISSUE THREAD

**Issue by henrjk** [opendevstack/ods-quickstarters#26]
Using the instructions on the wiki https://github.com/opendevstack/ods-quickstarters/wiki/Run-quickstarter-via-Jenkins.

I created a web hook also which fired successfully.

The initial quickstarter build - which generates the specific quickstarter instance and populates openshift resources - succeeded.
The subsequent webhook triggered build fails during testing.

Here some excerpts from the log:

```
...
INFO: ------------- Run sensors on project
INFO: Sensor Dependency-Check [dependencycheck]
INFO: Process Dependency-Check report
INFO: Dependency-Check XML report does not exists. Please check property sonar.dependencyCheck.reportPath:/tmp/workspace/henpg-cd/henpg-cd-be-golang-plain-1-master/${WORKSPACE}/dependency-check-report.xml
INFO: Analysis skipped/aborted due to missing report file
INFO: Dependency-Check HTML report does not exists. Please check property sonar.dependencyCheck.htmlReportPath:/tmp/workspace/henpg-cd/henpg-cd-be-golang-plain-1-master/${WORKSPACE}/dependency-check-report.html
INFO: HTML-Dependency-Check report does not exist.
>>> Not sure the above is an issue but it looks like the WORKSPACE reference is not resolved.
...
[henpg-cd-be-golang-plain-1-master] Running shell script
+ cat test-results.txt
+ go-junit-report
/tmp/workspace/henpg-cd/henpg-cd-be-golang-plain-1-master@tmp/durable-80367f27/script.sh: line 2: go-junit-report: command not found
cat: write error: Broken pipe```

**Comment by michaelsauter** [comment]
@henrjk This is probably be due to an outdated golang slave. We have an image tag named `1.2.x` internally, can you test against that?

**Comment by henrjk** [comment]
Will do.

**Comment by henrjk** [comment]
It works with 1.2.x.
Do we need to change anything or will the slave base be updated?

**Comment by michaelsauter** [comment]
Perfect. It's just that the internal `latest` tag has not been updated yet. Could you do that? Thanks!

**Comment by henrjk** [comment]
Ok I updated the image using tailor update from ods-quickstarters/common/jenkins-slaves/golang/ocp-config and then triggering a build.
After this the original Jenkinsfile now produced a green build.
