### ISSUE TITLE
Allow target branch configuration for a created quickstarter

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#271]
git-push.sh today commits the generated files to master by default - which means the first build/deploy happens in *-test env

https://github.com/opendevstack/ods-project-quickstarters/blob/master/boilerplates/git_push.sh#L28 

This may be wanted but should be configurable on global level. 

@michaelsauter - the idea is to commit "empty" to master, and then checkout the branch (if passed) to make the real commit there.. thoughts?

Update  - a jenkinsfile must exist in Master to Skip a build there.. otherwise the build of Master will blow up with cannot locate jenkinsfile of alike errors ...

**Comment by michaelsauter** [comment]
Closing this for now. Please reopen if you feel we still need this. I think we're ok with what we have. The "default" deploys into the `dev` env, and from that point on users can do whatever they want.
