### ISSUE TITLE
e2e-cypress: Update to nodejs10 image

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#29]
It is using nodejs8, which is really old.

**Comment by michaelsauter** [comment]
@cschweikert Could you please look into this?

**Comment by herrkoch** [comment]
Hey, I tested the cypress quickstarter with the nodejs10-angular Jenkins slave and also run an npm audit fix which updated cypress to 3.6.1. Also run `npm run-script all` locally and it executes fine (of course with zero tests). Jenkins build is also fine. Created a PR now.

**Comment by herrkoch** [comment]
I also realized that the node10-angular jenkins slave has cypress@3.3.1 preinstalled, we might to update the Jenkins slave as well or remove cypress there? Not sure.
