### ISSUE TITLE
be-gateway-nginx documentation is missing

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-quickstarters#292]
**Describe the bug**
Link on https://www.opendevstack.org/ods-documentation/opendevstack/3.x/quickstarters/index.html#_available_official_quickstarters to `be-gateway-nginx` is broken.

Link on site `* xref::be-gateway-nginx.adoc[Backend - Gateway/Nginx]` , but directory https://github.com/opendevstack/ods-quickstarters/tree/master/docs/modules/quickstarters/pages does not contain `be-gateway-nginx.adoc`

**Comment by michaelsauter** [comment]
@gerardcl Can you please look into this? Thanks!
