### ISSUE TITLE
NodeJS 10 slave image fails to build

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#295]
**Describe the bug**
```
Step 10/18 : ADD http://mirror.centos.org/centos/7.7.1908/os/x86_64/Packages/xorg-x11-server-Xvfb-1.20.4-7.el7.x86_64.rpm /root/xorg-x11-server-Xvfb.x86_64.rpm
error: build error: Got HTTP status code >= 400: 404 Not Found
```
**Affected version**
 - OpenDevStack: master

**Comment by gerardcl** [comment]
right! they reorganized! new link is:
http://mirror.centos.org/centos/7/os/x86_64/Packages/xorg-x11-server-Xvfb-1.20.4-10.el7.x86_64.rpm

tested locally
