### ISSUE TITLE
Idea: Move prov-app and doc-gen to their own repos

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#308]
This repo contains quickstarters that are part of the "official distribution" and therefore are also part of the default configuration of available quickstarters in the prov app.

The quickstarters for the prov-app and doc-gen deviate from that. They are not user-facing but target developers who want to contribute.

I was wondering if it would be better to co-locate the quickstarters within their own repos. Example:

Add a folder `quickstarter` into the repo `ods-provisioning-app`. The content of this `quickstarter` folder would be the same as we have in `ods-quickstarters/ods-provisioning-app` right now.

Benefits:

- If one needs to make a change to the prov app that also affects the quickstarter, one does not need to touch two repos
- ods-quickstarters does not contain quickstarters that are not part of the prov-app default config

Drawbacks:

- There's an implicit dependency from prov-app to the jenkins-slave-maven image. However, right now the situation is similar actually: the slave image is in the same repo, but it is not enforced

What are your thoughts on this? @oalyman @clemensutschig @gerardcl?

**Comment by gerardcl** [comment]
I am for cleaning it up. Makes sense and makes it leaner having such quickstarter folder in the respective repos.

The drawback related to the slave I think would be solved if we align all using the slaves from docker hub, right?

Question: do we need to make them provision-able via provision-app? I do not think so, right? let's make it simple and if one wants to develop just calls the right jenkins job <- so we might just need to assure developers know how to call externals jenkins jobs for provisioning

**Comment by michaelsauter** [comment]
Yes I would not expose them by default on the prov app. One can add it (e.g. for BI X that might make sense), but not by default.

**Comment by metmajer** [comment]
@michaelsauter doc-gen would still be provisioned with the release manager, right?

**Comment by michaelsauter** [comment]
@metmajer Yes this would be completely unrelated. It's just which repo hosts the quickstarter code. But since this hasn't gotten much traction / priority I think we just leave it as it is ...
