### ISSUE TITLE
fe-react: Generated Jenkinsfile should use nodejs10 slave image

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#31]
At the moment it uses nodejs8. The provisioning Jenkinsfile is already correct.

**Comment by michaelsauter** [comment]
@ManuelFeller As you mentioned the quickstarter works with nodejs10, could you please open a PR for it? That would be great!

**Comment by ManuelFeller** [comment]
Was busy at Friday afternoon and the weekend, but here we go... ;-)
