### ISSUE TITLE
Switch from typescript to Js for node-express quickstarter

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-quickstarters#315]
**Is your feature request related to a problem? Please describe.**
Yeoman [generator](https://github.com/opitzconsulting/generator-node-express-typescript) isn't maintained frequently and makes it more difficult to maintain this quickstarter. 
Is anyone in favor of switching to another scaffolding tool, sticking to this one or quickstart with a clean JS express [generator](https://expressjs.com/en/starter/generator.html)? 

Here's a related [suggestion](https://github.com/opendevstack/ods-quickstarters/issues/88#issuecomment-582464267) from the past by @velcrin

**Comment by michaelsauter** [comment]
I found https://www.npmjs.com/package/express-generator-typescript. Maybe also worth a try?

**Comment by akhilsoman** [comment]
> I found https://www.npmjs.com/package/express-generator-typescript. Maybe also worth a try?

Yes, this looks promising. I have tested it locally and it generates a very minimal express application with typescript

**Comment by sino92** [comment]
Nice, same as @akhilsoman suggested earlier. Would be curious to hear out what others think @ManuelFeller @m-apsolon @rianet @ultrasonicsoft @bljubisic @rattermeyer @velcrin @cschweikert @herrkoch @netzartist

**Comment by bljubisic** [comment]
I have not tried it, but I will in next couple of days. I am all for typescript though :)

**Comment by velcrin** [comment]
I also stumbled upon [express-generator-typescript](https://www.npmjs.com/package/express-generator-typescript) and it seems pretty opinionated. It does not only set up express and ts, it adds concepts such as `entities`, `logging`, `dao`, `multi env`, ... Do we want to go there a quickstarter?

**Comment by netzartist** [comment]
Maybe this would fit, too (no experience with it): https://github.com/bitjson/typescript-starter

**Comment by cschweikert** [comment]
* express-generator-typescript: looks nice except the dao and entities as @velcrin mentioned. Coverage analysis support might need to be added.
* typescript-start: doesn't preinstall anything express-related. Beside that it looks nice, presets a lot of usefull things like coverage analysis, prettier, vscode debug support, ...

Either we stick to a good but not perfect generator solution, or we provide and maintain a full example app ourself. I guess express-generator-typescript is a quick win for now.

**Comment by velcrin** [comment]
A third alternative could be to use the official [express-generator](https://expressjs.com/en/starter/generator.html) and just add typescript support by adding a `tsconfig`, replacing the `start: "node ./bin/www"` with `start: "ts-node ./bin/www"` and adding a build step to Jenkins using `tsc` and populating the `docker` folder. Code in the repo would still be js but the quickstarter would support ts out of the box.

**Comment by cschweikert** [comment]
Since ``express-generator-typescript`` already comes along with a lot of good stuff in terms of build logic I guess it would be the easiest to just start with a copy of this and reduce most of the example content (mainly the content of the ``src`` folder) towards a minimum hello world app.

**Comment by rianet** [comment]
I would vote for selecting the official `express-generator` and adjust the typescript support. 
`typescript-starter` is not well maintained (last updated on Sept 9 2019)
`express-generator-typescript` could also have the risk of not being maintained in the future.

**Comment by herrkoch** [comment]
I wonder whether we should keep that generator step at all or rather put a standard structure (let it be generated or manually created) with TypeScript support into the quickstarter. That could possibly be already extended by some scaffolding for implementing a REST or GraphQL API which is our most common use case, I think. (As a quickfix I'd be also fine using any of these generators though.)

**Comment by sino92** [comment]
After some consideration, I've concluded it's the best approach to maintain without relying a third party scaffolding library. I also see it better to keep it most simple for the developer and not enforce any conventions. 
So the new node-express quickstarter will come with almost bare minimum:
- typescript 
- express 
- @types/node
We'll configure a standard `tsconfig` with `--skipLibCheck` `--outDir "./dist"`, the developer will have the option to run `npm start` that executes the transpiled `index.ts` file, `tsc --watch & node dist/index.js` 
The quickstarter will feed`index.ts` file which composes of 5 lines of code starting a server and listening on a port.
