### ISSUE TITLE
extend quickstarter tests - to reflect a real installation qualification

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#347]
**Is your feature request related to a problem? Please describe.**
Cover all quickstarters with tests - similar to https://github.com/opendevstack/ods-quickstarters/tree/master/tests/be-typescript-express

- [x] provision each quickstarter
- [x] verify build and deployment
- [x] verify sq scan where applicable
- [x] verify nexus upload? 

related to opendevstack/ods-core#646

**Comment by clemensutschig** [comment]
@martsec  - @jafarre-viewnext - will this be covered in the E2E tests - you folks currently build?

**Comment by martsec** [comment]
I  don't think we are testing all the quickstarters right now.  Release manager yes, and one or two of the others is what I am seeing in the tests. For a given quickstarter we check the installation to bb and jira, the build and deployment but we might be missing the sq scan and the nexus upload, right @jorge-romero ??

**Comment by clemensutschig** [comment]
we are making huge progress on this @georgfedermann - thanks a lot for helping :)

growing list: 
https://github.com/opendevstack/ods-quickstarters/tree/master/tests

**Comment by clemensutschig** [comment]
we are covering all quickstarters now ... finally ... and all of them build against nexus, so nexus functionality is verified ´....
