### ISSUE TITLE
SonarQube exclusions Coverage (fe-angular)

### ISSUE THREAD

**Issue by decarialeonardo** [opendevstack/ods-quickstarters#360]
**Is your feature request related to a problem? Please describe.**
While checking the SonarQube analysis in our frontend project, we’ve seen that in the initial sonar properties, we were missing some “sonar.coverage.exclusions”.

**Describe the solution you'd like**
There are a couple of exclusions that we think could be placed as default for any angular project.
The exclusions we added are:
`src/environments/**,**/*.module.ts`

**Additional context**
- The first one, are the environment files. In there we have the different properties used, and the sonarQube asks us to test that the file is well exported. (see next screenshot).
![img1](https://user-images.githubusercontent.com/2902162/86919606-ca977e80-c128-11ea-8652-e8687c489a36.jpg)

- The second one, in our case we agree that in the module files there should be no logic added. So is the place where the dependencies are imported, exported, injected,… but there is no further logic. (This one may be more susceptible to have some logic in some other project and have to be checked by sonar even is not a common practice)
![img2](https://user-images.githubusercontent.com/2902162/86919691-ebf86a80-c128-11ea-8fc7-c623062f03fb.jpg)

Regards,
Leo

**Comment by michaelsauter** [comment]
@cschweikert @rianet @ManuelFeller @bljubisic @netzartist What do you think?

**Comment by ManuelFeller** [comment]
For the environment files I agree - they should only contain some configuration parameters and could be excluded from the coverage test.

The `**/*.module.ts` also sounds OK for me (we could give a hint in the readme that we follow the "no logic in there rule" and you may have to change the sonar configuration if you differ), but there I would like to have the others opinions...

**Comment by cschweikert** [comment]
Also sounds good to me. Let's exclude them and mention the module files in the readme as @ManuelFeller suggested.

**Comment by rianet** [comment]
I don't see any issues about excluding them. I've never seen a module nor environment file that contains business logic. But there could be cases; I agree that if you have a different setup depending of your team agreements, it's up to you to update the sonar config to fit your needs.

**Comment by michaelsauter** [comment]
Cool!

@decarialeonardo do you want to open a PR for this? The properties template is at https://github.com/opendevstack/ods-quickstarters/blob/master/fe-angular/sonar-project.properties.template.

@ManuelFeller @rianet @cschweikert Should similar configuration be made for Ionic?

**Comment by cschweikert** [comment]
I already started for fe-angular
