### ISSUE TITLE
enable WSGI for ds-ml-service quickstarter

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#37]
**Is your feature request related to a problem? Please describe.**
Currently, when `ds-ml-service` is deployed, all services are just running flask. The recommended and minimal practice for being production ready is to make use of a [WSGI](https://www.python.org/dev/peps/pep-3333/) server implementation, so to later (if required: caching, high request loads,...) being able to proxy it through a proper HTTP server via HTTP or socket connections.

**Describe the solution you'd like**
Make use of an already existing WSGI implementation (e.g.: uWSGI or Gunicorn) and spinup flask through it.

**Describe alternatives you've considered**
Also loading an HTTP server on top (e.g.: Nginx) --> out of scope since there is not expected high loads nor cache required (only API) <-- not required

**Additional context**
The implementation should be as transparent as possible to current ds-ml-service design.
This activity was started and already merged in ods-project-quickstarters ([#430](https://github.com/opendevstack/ods-project-quickstarters/issues/430))

**Comment by michaelsauter** [comment]
@gerardcl Is this still open or done now?

**Comment by gerardcl** [comment]
it is done for `ds-ml-service`
missing `be-python-flask`
I will try to make if happen for ODS2, if not in time I will split and move half to ODS3

**Comment by michaelsauter** [comment]
@gerardcl Do you think you can still get this done by the end of tomorrow? Otherwise I am totally fine with moving this to ODS 3.

**Comment by gerardcl** [comment]
Let's move it to ODS 3, no rush on this. 
Indeed, I am planning to provide other enhancements in the be-python-flask one (also related to the testing framework, since nose is no longer maintained)

**Comment by michaelsauter** [comment]
@gerardcl Could you please open a new issue then where you describe this, and then we can close this? That would be great!

**Comment by gerardcl** [comment]
closed via https://github.com/opendevstack/ods-quickstarters/commit/85b90cc91e55f74127d6b70b9ee3d64675ae7aea
