### ISSUE TITLE
Update Ionic Quickstarter to @ionic/cli

### ISSUE THREAD

**Issue by ManuelFeller** [opendevstack/ods-quickstarters#380]
**Is your feature request related to a problem? Please describe.**
The old `@ionic` package is deprecated; `@ionic/cli` is the successor and should be used.
Also more consistent use of yarn / npm would be good...

**Describe the solution you'd like**
Update to the latest CLI that works in the build image and fully switch to npm

**Describe alternatives you've considered**
staying on an outdated version..?

**Additional context**
-

**Comment by ManuelFeller** [comment]
So while working on this and testing with `@ionic/cli` in version 6.3.0 on node version 10.15.1 two things that I was not aware of came up:

- the used Angular version does no longer obey the `--single-run` parameter on `ng test`, leading to a not closing chrome -> does not work with CI out of the box
- I did not find a way (yet) to make a non-interactive install with a cordova integration since even the `ionic start yourproject blank --cordova` leads to the following interactive request:

```
[WARN] About to integrate your app with Cordova.
       
       We now recommend ⚡️ Capacitor⚡️  (https://ion.link/capacitor) as the official native runtime for Ionic. To
       learn about the differences between Capacitor and Cordova, see these docs[1]. For a getting started guide, see
       these docs[2].
       
       [1]: https://ion.link/capacitor-differences-with-cordova-docs
       [2]: https://ion.link/capacitor-using-with-ionic-docs
       
? Are you sure you want to continue? (Y/n)
```
When you try `--no-interactive` added to the call this will be answered with no, leading to a not executed integration.

I see two possible solutions for new Ionic apps:
Not adding any integration and maybe adding the instructions how to start the integration (run `ionic integrations enable cordova` / `ionic integrations enable capacitor`) to the `README` - or going with capacitor (which may lead to issues later since not all Cordova plugins work with it for sure).

I personally vote for keeping the integration open solution since it allows the project to choose - what do you think @cschweikert @rianet @bljubisic 

And regarding the karma not closing Chrome issue I will check what solutions could work, maybe I go for a customized karma config or something like that...

**Comment by cschweikert** [comment]
Have you tried running it with ``CI=true npm run ...`` or so on your local machine? The environment variable ``CI`` is usually used to determine CI/CD tools running the script, which again leads to a different behavior. ``ionic srtart`` for example doesn't ask any questions anymore, if you apply ``CI=true``.

**Comment by cschweikert** [comment]
about ``--single-run``: I red something about that this parameter somehow moved into ``karma.conf.js``. In the one provided with ``fe-ionic/files/karma.conf.js`` it actually says ``singleRun: false``. Maybe it needs to be changed to ``true``.

**Comment by ManuelFeller** [comment]
> @ManuelFeller Have you tried running it with `CI=true npm run ...` or so on your **local machine**? The environment variable `CI` is usually used to determine CI/CD tools running the script, which again leads to a different behavior. `ionic srtart` for example doesn't ask any questions anymore, if you apply `CI=true`.

Yes, I tried many ways like `--no-confirm`, `--no-interactive`and variants of these to actually get a `y` passed into there. But they (as well as `CI=true`) all get translated to saying `no`, adding
````

--no-confirm: Are you sure you want to continue? No
--no-confirm: Integrate your new app with Capacitor to target native iOS and Android? No
```
to the above outputs - so even if we select `--cordova` explicitly it will be interpreted as a `no`.

Since we did not specify an integration before either I would vote for staying that way and giving the user the choice when they really need it, but giving a heads up how to do so in the `README`...

**Comment by ManuelFeller** [comment]
> about `--single-run`: I red something about that this parameter somehow moved into `karma.conf.js`. In the one provided with `fe-ionic/files/karma.conf.js` it actually says `singleRun: false`. Maybe it needs to be changed to `true`.

Saw that too, and new projects made with `ionic start` also get generated with that setting in there. Will check what else may need to be adjusted and then decide if I modify the generated or just override it with a predefined one ;-)

**Comment by cschweikert** [comment]
Yeah, I guess you are right. Let's add it to the ``README`` as you proposed.

**Comment by rianet** [comment]
I'm also okay with no capacitor or cordova integration. Updating the ```README``` should be fine. In later version of prov app when we can specify params we can enhance this.
