### ISSUE TITLE
Pass image tag and Git ref as params

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#41]
The `Jenkinsfile.template` references a specific branch of the sharedd library (e.g. `production`) and an image tag (e.g. `latest`) of a Jenkins slave.

Those have to be customised with every release which is annoying.

I've come up with the idea to make those references variables, as the file is rendered anyway. I'd pass down the value from the provisioning app (which can take it from configuration).

@kiwo @gerardcl Unless you have strong feelings against this, I'd implement that this week.

**Comment by kiwo** [comment]
you could just configure them via the quickstaer Jenkinsfile (springCliVersion is being set in this file for example) or perhaps within the jenkins-slave-maven pod. i am not shure what you are trying to accomplish.

**Comment by michaelsauter** [comment]
I want to accomplish that:

* We do not have to modify any source code when doing releases (as for a release, you usually want to fix the image tags etc. - e.g. point to `1.2.x`)
* When someone wants to test a quickstarter, and needs a specific image tag for this, that they can pass it as a parameter
