### ISSUE TITLE
e2e cypress quickstarter lacks stage for sonar testing

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#411]
**Describe the bug**
The e2e cypress test - https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-cypress/Jenkinsfile.template#L11-L13 lacks stage for sonarqube scanning

**Expected behavior**
Similar stages as e2e-spock - https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/Jenkinsfile.template#L13

**Affected version (please complete the following information):**
 - OpenDevStack [master / 3.x]

**Additional context**
As part of the the quickstarter quality mgmt - we strive for harmonization of quickstarters and stages in there

**What needs to be fixed?***
1. addition of scanFor.. stage, including sonar properties
1. additions in the sonar test (https://github.com/opendevstack/ods-quickstarters/blob/master/tests/e2e-cypress/jenkinsfile_test.go) - similar to https://github.com/opendevstack/ods-quickstarters/blob/master/tests/e2e-spock-geb/jenkinsfile_test.go#L97-L137 (please wait for the PR to be merged!)
1. addition in the golden stage record: https://github.com/opendevstack/ods-quickstarters/blob/master/tests/e2e-cypress/golden/jenkins-build-stages.json

related to & waiting for #409

**Comment by clemensutschig** [comment]
@herrkoch can you Pick this up? @michaelsauter fyi

**Comment by michaelsauter** [comment]
We talked about this in the last JF, @oalyman is on it.

**Comment by michaelsauter** [comment]
Fixed by #428.

**Comment by herrkoch** [comment]
Thanks @oalyman for fixing this during my absence!
