### ISSUE TITLE
Lets upgrade to the latest python 3.8

### ISSUE THREAD

**Issue by henrjk** [opendevstack/ods-quickstarters#415]
**Is your feature request related to a problem? Please describe.**
The be-python-flask, ds-ml-service, ds-jupyter-notebook and the python agent are still on 3.6 and we should go to the latest 3.8 (currently 3.8.5).

**Describe the solution you'd like**
I think for the deployed images these should be based on the [3.8.5-buster](https://github.com/docker-library/python/blob/44ded7c92b0c20abbeaa88785751eb0822d05ced/3.8/buster/Dockerfile) which should also allow for packages needing C compilation.  

**Describe alternatives you've considered**
The slim image could be used for having a more lightweight image, but I think allowing C packages is more important to most users

**Additional context**
Ideally this should go into ODS3

**Comment by michaelsauter** [comment]
@henrjk Release of 3.0 is targeted on Friday - do you think you can make it till then? Further, do we expect any compatibility issues with existing components?

FYI @renedupont

**Comment by gerardcl** [comment]
hi! we will try! and yes, we are taking into account current existing components and even existing use cases

**Comment by hugowschneider** [comment]
Some Python Docker inspiration from RH:

https://catalog.redhat.com/software/containers/rhscl/python-38-rhel7/5e838896dd19c7789613d625?container-tabs=dockerfile
