### ISSUE TITLE
Scala Play fails to boot

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#433]
**Describe the bug**
Scala Play quickstarter fails to boot:
```
Oops, cannot start the server.
--
  | Configuration error: Configuration error[
  | The application secret has not been set, and we are in prod mode. Your application is not secure.
  | To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret
  | ]
  | at play.api.Configuration$.configError(Configuration.scala:155)
```

Looks like we should set the secret during provisioning at https://github.com/opendevstack/ods-quickstarters/blob/master/be-scala-play/be-scala-play.g8/src/main/g8/conf/application.conf#L4

**To Reproduce**
1. Provision quickstarter
2. Wait for component build to finish
3. Show logs of deployment

**Expected behavior**
First deploy should work without errors.

**Affected version:**
 - OpenDevStack: master

FYI @renedupont blocker for the 3.0 release

**Comment by clemensutschig** [comment]
@oalyman Status? 
@michaelsauter can you add a pod Check?

**Comment by michaelsauter** [comment]
@clemensutschig The check looks fine to me actually. However, I noticed another strange behaviour with it yesterday but can't say yet why it is happening. The code looks correct to me.
