### ISSUE TITLE
Jenkins agent NodeJS12 missing in Makefile

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-quickstarters#469]
**Is your feature request related to a problem? Please describe.**
When installing the Jenkins agents as part of the ODS3.x installation, we have realized that the Jenkins agent NodeJS12 is missing from the [Makefile](https://github.com/opendevstack/ods-quickstarters/blob/3.x/Makefile#L11). This results in a missing image in the ImageStream, not making it available for customers.

**Describe the solution you'd like**
I'd like Jenkins agent NodeJS12 to be included in the [Makefile](https://github.com/opendevstack/ods-quickstarters/blob/3.x/Makefile#L11) so that users can build their apps using the NodeJS12 version.

What do you think?

**Comment by michaelsauter** [comment]
This was on purpose. The NodeJS 12 agent image was added to the repo, but the quickstarters were not ported to it. To keep the installation as minimal, we left out the agent image in the Makefile as the image is not actually used anywhere. It would be great to get rid of the NodeJS 10 agent image for ODS 4.

**Comment by gerardcl** [comment]
I added "breaking change" label, since moving from node 10 to 12 will be a breaking change

**Comment by michaelsauter** [comment]
@gerardcl Is it really breaking? If so, do you know more about what breaks? Would be good if we can link to some documents describing the impact ...

**Comment by gerardcl** [comment]
to me it is only a breanking change if we do not provide node 10 in next release, but for sure it is not since node 10 will be still available in previous ODS versions, true!

**Comment by michaelsauter** [comment]
This has been done on master already.
