### ISSUE TITLE
Error deploying Dockerplain Quickstarter (ODS 3.x) with Release Manager

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-quickstarters#471]
**Describe the bug**
When deploying a completely brand-new Dockerplain Quickstarter (ODS 3.x) using Release Manager, the Jenkins pipeline fails.

**To Reproduce**

Assuming the customer has a Dockerplain Quickstarter (ODS 3.x),

1. Go to the Jenkins portal of the existing project.
2. Create and launch a new release in the MRO pipeline.
3. Scroll down to the Jenkins logs of that build execution.
4. See error in the log output (further below).

**Expected behavior**
When deploying a completely brand-new Dockerplain Quickstarter (ODS 3.x) using Release Manager, the MRO Jenkins pipeline should build the Docker image successfully.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.x

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
DEBUG: Collecting JUnit XML Reports ('unit') for registration-service
[Pipeline] dir
Running in /var/lib/jenkins/jobs/****-cd/jobs/****-cd-****-mro-pipeline-master/workspace/xunit/registration-service/unit
[Pipeline] {
[Pipeline] unstash
[Pipeline] echo
2020-10-07 15:22:39Z Could not find any files of type 'JUnit XML Report' to unstash for name 'test-reports-junit-xml-registration-service-5'
[Pipeline] }
[Pipeline] // dir
[Pipeline] echo
WARN: Error: unable to unstash JUnit XML reports, type 'unit' for repo 'registration-service' from stash 'test-reports-junit-xml-registration-service-5'.
```

**Additional context**

**Comment by michaelsauter** [comment]
@SHoen isn't that the exact same error you were seeing in one of your components that had no tests?

**Comment by SHoen** [comment]
@michaelsauter yes of course. After updating the release manager from 2.x to 3.x I am experiencing the same issue.

**Comment by jssnull** [comment]
Hi, 
I've the same issue in quickstarter: be-fe-mono-repo-plain
https://github.com/opendevstack/ods-quickstarters/issues/472

**Comment by metmajer** [comment]
@michaelsauter @felipecruz91 @jssnull please consult the documentation for this Quickstarter. Also note that any ODS component of type `ods` (default) in the release manager's `metadata.yml` must deliver unit test results. With the current information, I consider this bug to be invalid.

**Comment by metmajer** [comment]
@borja44 @jssnull documentation can be found here, please check it out: https://github.com/opendevstack/ods-quickstarters/blob/master/docs/modules/quickstarters/pages/docker-plain.adoc

**Comment by felipecruz91** [comment]
Thanks, @metmajer. It is now clear to me that, based on the documentation, unit tests are required.

Interestingly enough, I am aware of the existence of a Docker plain quickstarter component with _no_ unit tests that happens to build successfully in Jenkins (`Finished: SUCCESS`), as shown in the image below.

![image](https://user-images.githubusercontent.com/15997951/96101958-477b8680-0ed6-11eb-9159-5ec074704099.png)

Shouldn't that Jenkins pipeline build fail because of the lack of unit tests, as per the docs? I'd be interested in knowing why, two Docker plain quickstarters that to my understanding are identical, present a different behaviour.

**Comment by felipecruz91** [comment]
@metmajer After comparing carefully the Jenkins build logs of both projects (the one that works and the one that doesn't), we have identified that the ODS project that does *not* contain the `cd-user-bitbucket-token` secret in their `-cd` namespace will fail.

In summary, the error had absolutely nothing to do with the fact of the project having unit tests defined or not (it was a misunderstanding due to Jenkins build breaking just after the `No xUnit results found!!` message).

Therefore, for the Dockerplain quickstarter or any other to work successfully, the project in OpenShift must contain the `cd-user-bitbucket-token` secret in their `-cd` namespace.

P.S. Note that I still haven't figured out the reason why that secret was not created as part of the ODS project creation.

**Comment by metmajer** [comment]
@felipecruz91 thanks for investigating further and providing an answer yourself. Please note that a component pipeline without a Release Manager context will never fail because of missing tests. However, when run in a Release Manager context, it will be asserted that a component of `type: ods` (= code) produces unit tests since as demanded by compliance. I hope this information helps gain a better understanding, even if it's not related to the solution.

**Comment by metmajer** [comment]
@felipecruz91 please open a new issue for the secret-related bug.
