### ISSUE TITLE
repeated be-fe-mono-repo-plain builds fail in jenkins due to (...)

### ISSUE THREAD

**Issue by jssnull** [opendevstack/ods-quickstarters#472]
**Describe the bug**
If we create a new application using quickstarter be-fe-mono-repo-plain 
Every build in Jenkins due to missing xunit xmls
 
**To Reproduce**
1. Go to provisioning application
2. Create new be-fe-mono-repo-plain quickstarter
3. Launch a new build of your application (Trigger a new commit for example)
4. Check your new application build logs in Jenkins
5. Your application build will crash due to missing xunit xml files

**Expected behavior**
Application builds shouldn't fail

**Screenshots**
Jenkins screenshots
![image](https://user-images.githubusercontent.com/12979859/95831300-2598cd00-0d39-11eb-8d3b-f2da3342b008.png)
![image](https://user-images.githubusercontent.com/12979859/95831430-4e20c700-0d39-11eb-9d95-89b9468f3e94.png)
![image](https://user-images.githubusercontent.com/12979859/95831349-33e6e900-0d39-11eb-8de2-08a3d11a3c88.png)

**Affected version (please complete the following information):**
 - OpenShift: [e.g. 3.9, 3.11]
 - OpenDevStack [e.g. 1.0, 1.1]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```bash
Attempting to stash testresults from location: 'build/test-results/test'
[Pipeline] sh (Moving test results to system location: build/test-results/test)
+ mkdir -p build/test-results/test build/test-results/test
+ cp -rf 'build/test-results/test/*' build/test-results/test
+ true
cp: cannot stat 'build/test-results/test/*': No such file or directory
[Pipeline] sh (Counting test results in build/test-results/test)
+ ls -la 'build/test-results/test/*.xml'
+ wc -l
ls: cannot access build/test-results/test/*.xml: No such file or directory
[Pipeline] echo
No xUnit results found!!
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

**Additional context**

**Comment by metmajer** [comment]
@jssnull @borja44 I expect some more drive from the support team behind this. What have you tried so far?

**Comment by clemensutschig** [comment]
Can we please get the entire log? The ci tests show that this is working...

**Comment by metmajer** [comment]
@jssnull @clemensutschig absolutely, the "No xUnit results found!!" does not trigger an error. The failing `ls` might do it though.

**Comment by clemensutschig** [comment]
> @jssnull @clemensutschig absolutely, the "No xUnit results found!!" does not trigger an error. The failing `ls` might do it though.

No.. this is bullet proof

**Comment by clemensutschig** [comment]
ok - as suspected the problem is somewhere else (patchBCConfig)

```
[Pipeline] sh
+ oc -n odsl3t-dev patch bc mono-jss-frontend --type=json --patch '[{"op": "replace", "path": "/spec/source", "value": {"type":"Binary"}},{"op": "replace", "path": "/spec/output/to/name", "value": "mono-jss-frontend:6aec486d"},{"op": "add", "path": "/spec/output/imageLabels", "value": [
              {"name": "ods.build.source.repo.url", "value": "https://xxxxx/scm/odsl3t/odsl3t-mono-jss.git"},{"name": "ods.build.source.repo.commit.sha", "value": "xxxxx"},{"name": "ods.build.source.repo.commit.msg", "value": "Jenkinsfile edited online with Bitbucket"},{"name": "ods.build.source.repo.commit.author", "value": "zxBCN Santiago,Jairo (IT EDS) EXTERNAL (jairo.santiago.ext@boehringer-ingelheim.com)"},{"name": "ods.build.source.repo.commit.timestamp", "value": "2020-10-13 09:02:22 +0200"},{"name": "ods.build.source.repo.branch", "value": "master"},{"name": "ods.build.jenkins.job.url", "value": "https://xxxxx/job/odsl3t-cd/job/odsl3t-cd-mono-jss-master/30/"},{"name": "ods.build.timestamp", "value": "Tue Oct 13 07:04:59 UTC 2020"},{"name": "ods.build.lib.version", "value": "3.x"}
            ]}]'
The  "" is invalid
``` 

@michaelsauter  - any idea ... ?

**Comment by clemensutschig** [comment]
so
```
$ oc -n odsl3t-dev patch bc mono-jss-frontend --type=json --patch '[{"op": "replace", "path": "/spec/source", "value": {"type":"Binary"}},{"op": "replace", "path": "/spec/output/to/name", "value": "mono-jss-frontend:6aec486d"}]'
```

reproduces this - without
```
{"op": "replace", "path": "/spec/output/to/name", "value": "mono-jss-frontend:6aec486d"}
```

it works

**Comment by jssnull** [comment]
I tried the same use case in another installation of ODS and worked well

**Comment by michaelsauter** [comment]
The only thing I can think of is that the BC was in some kind of weird state where the patching failed to apply? @jssnull Did you do any manual changes to the BC?

**Comment by jssnull** [comment]
Hi, @michaelsauter  I didn't changed the BC manually
