### ISSUE TITLE
Integrate R packages building, artifacting and deploying within ODS, Nexus and SonarQube

### ISSUE THREAD

**Issue by stevegbrooks** [opendevstack/ods-quickstarters#473]
It would be nice to have a quickstarter for building R packages and getting them up on Nexus for end-users to download and install. Now that the new version of Nexus (as of September) supports R packages, this is a use case we'd like to develop in BDS for statistics and building modular web apps. 

Here's the Jenkinsfile we've been using so far, but we're not yet taking advantage of SonarQube (which doesn't have R support without a third-party plugin) or Nexus (which does).

def final projectId = 'xxxx'
def final componentId = 'dataloader'
def final credentialsId = "${projectId}-cd-cd-user-with-password"
def sharedLibraryRepository
def dockerRegistry
node {
  sharedLibraryRepository = env.SHARED_LIBRARY_REPOSITORY
  dockerRegistry = env.DOCKER_REGISTRY
}

library identifier: 'ods-library@2.x', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: sharedLibraryRepository,
   credentialsId: credentialsId])

/*
  See readme of shared library for usage and customization
  @ https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/README.md
  eg. to create and set your own builder slave instead of 
  the base slave used here - the code of the base slave can be found at
  https://github.com/opendevstack/ods-core/tree/master/jenkins/slave-base
 */ 
odsPipeline(
  projectId: projectId,
  componentId: componentId,
  branchToEnvironmentMapping: [
    'master': 'test',
    '*': 'dev'
  ],
	podContainers:[
      containerTemplate(
        name: 'jnlp',
        image: "${dockerRegistry}/cd/jenkins-slave-base:2.x",
    	workingDir: '/tmp',
    	alwaysPullImage: true,
    	args: '${computer.jnlpmac} ${computer.name}'
      ),
    containerTemplate(
      	name: 'rocker',
    	image: "rocker/tidyverse:latest",
    	workingDir: '/tmp',
      	alwaysPullImage: true,
      	ttyEnabled: true,
      	resourceRequestCpu: '100m',
      	resourceLimitCpu: '750m',
      	resourceRequestMemory: '1Gi',
      	resourceLimitMemory: '2Gi',
      	command: 'cat'
    ),
  ],  
  openshiftBuildTimeout: 45,
  testResults: 'tests'
) { context ->
  container('rocker') { 
    stageBuild(context)
  	stageUnitTest(context)
  }
  /*
   * if you want to introduce scanning, uncomment
   * 
   * stageScanForSonarqube(context)
   */ 
  /*
  * stageStartOpenshiftBuild(context)
  * stageDeployTemplate(context)
  * stageDeployToOpenshift(context)
  */
}

def stageBuild(def context) {
  stage('Build') {
    sh "Rscript ./build.R"
  }
}

def stageUnitTest(def context) {
  stage('Unit Test') {
  }
}

**Comment by gerardcl** [comment]
Hi @stevegbrooks, 

What about "Integrate R packages building, artifacting and deploying within ODS, Nexus and SonarQube"?

IMHO we do not need a quickstarter for just that purpose, but to provide from the ODS core and its library such support.

If you agree, then we can create three separate issues for:
- `ods-core`: "add R packages support on Nexus repository"
- `ods-jenkins-shared-library`: "provide R packaging support" , and/or , in `ods-quickstarters`:  "R Jenkins agent for packaging support"
- `ods-core`: "add R language SonarQube plugin"

Does it make sense?

P.S.: Please, just in case, remember to not provide internal information such project names or URLs or credentials.

**Comment by stevegbrooks** [comment]
sounds good - i'll edit the current and add the three you suggest. thanks
