### ISSUE TITLE
Transition quickstarters from NodeJS 10 to NodeJS 12

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#483]
We already have a NodeJS 12 agent image, but it is not installed by default, and not used by any quickstarter, see https://github.com/opendevstack/ods-quickstarters/issues/469. Also, the NodeJS 12 image does not contain necessary dependencies for E2E tests (e.g. with Cypress).

For ODS 4, I suggest we:

* remove the `nodejs10-angular` agent image
* add the required dependencies (chrome, xvfb) to the `nodejs12` agent images
* switch all quickstarters to use `nodejs12`

As a consequence, users who want to adopt ODS 4 also need to move from NodeJS 10 to 12.

Why 12 and not 14? RedHat also only offers 12 (https://github.com/openshift/jenkins/tree/master/agent-nodejs-12), so I think we should stick with this.

Objections @metmajer @clemensutschig @cschweikert @ManuelFeller @m-apsolon?

**Comment by m-apsolon** [comment]
sounds like an excellent idea to me.

**Comment by clemensutschig** [comment]
doc impact & test impact (check for the right agent image)
