### ISSUE TITLE
Update maven version in maven-agent

### ISSUE THREAD

**Issue by renedupont** [opendevstack/ods-quickstarters#484]
**Is your feature request related to a problem? Please describe.**
In the maven-agent we bake maven in version 3.3 into the agent. This is a few years old now and the latest version is 3.6.3. I had recently the case that a quickstarter (https://github.com/opendevstack/extra-quickstarters/pull/7#discussion_r521605532) required a more recent maven version. The occasions where a more recent version is required may potentially go up over time.

**Describe the solution you'd like**
Update it to the latest available version.

**Describe alternatives you've considered**
- Leave it like it is and install later maven version in the Dockerfile of the specific quickstarter which is painful to do and takes time and bandwith every build
- Wait for maven 3.7

**Additional context**
I'm not sure about backwards compatibility of maven versions yet.

**Comment by michaelsauter** [comment]
Updating Maven would be very welcome! However, I'd like to align with RedHat here, and they are on Maven 3.5: https://github.com/openshift/jenkins/tree/master/agent-maven-3.5. Would this be "new enough"?

**Comment by renedupont** [comment]
Nope, my use case (bootstrapping of a quarkus app) requires maven 3.6.2+. 
But since I have to use maven only for the bootstrapping part (for building the app gradle is been used) I could just continue in the meantime to install the latest maven 'on the fly' because this part will only run when a new quarkus quickstarter is being provisioned.

**Comment by stitakis** [comment]
@michaelsauter @renedupont btw... if we upgrade maven (or gradle, etc) how do we test if the newer version doesn't break maven builds that were based in the former maven version?

**Comment by michaelsauter** [comment]
@stitakis I believe there isn't much we can do. We can read what the Maven project has to say about compatibility between 3.3 and 3.5. In case there is a breaking change, there is probably nothing we can do about it. In any case, we should communicate any version change in the upgrade guides. On ODS 3.x, there should not be a version change, so people staying on that will not experience build failures. However, ODS 4.x being a major version is allowed to introduce breaking changes and we need to make people aware that when they adopt ODS 4.x, it also means updating Maven from 3.3 to 3.5.

**Comment by stitakis** [comment]
@michaelsauter sounds good to me, thanks for the clarification!

**Comment by michaelsauter** [comment]
Setting this for ODS 4. Also marking as "breaking change" until we figure out that it is actually non-breaking indeed.

@renedupont Do you want to follow this up?
