### ISSUE TITLE
e2c-cypress quickstarter - implement evidence and test similar to e2e-Spock/Geb

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#488]
follow up from opendevstack/ods-quickstarters#487

**Comment by clemensutschig** [comment]
the key here is
1. To implement the helper methods in the SpecHelper for evidence
1. To implement the acceptance test (against w3c school site) - to use the methods implemented above

**Comment by metmajer** [comment]
@ManuelFeller any update on this?

**Comment by ManuelFeller** [comment]
Sorry, pretty busy with other things currently; quite some stuff came up lately :( need to find a slot to align with @netzartist when we can actually tackle this

**Comment by metmajer** [comment]
@ManuelFeller @netzartist we have a rather large customer who depends on the Cypress quickstarter to implement evidence generation. Do you see a chance to implement the change early next week?

**Comment by clemensutschig** [comment]
I am playing currently with it - to at least come up with a dirty mvp of how it could look like :)

**Comment by clemensutschig** [comment]
a small helper method - all needed to get starting
