### ISSUE TITLE
Missing file in nodejs10-angular

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-quickstarters#500]
**Describe the bug**
When installing ODS 3.1 in one of our non-regulated clusters, the Jenkins agent image `nodejs10-angular` could not be installed due to an error with a missing file. This was part of the `make install-jenkins-agent` command.

**To Reproduce**
1. Go to `ods-quickstarters`
2. Run `make install-jenkins-agent`
3. See error below

**Expected behavior**
I'd expect the  `nodejs10-angular` image to be built successfully and be pushed to the image stream.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.1.0

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
make install-jenkins-agent
...
(some log messages ommited)
...
Uupdating bc/jenkins-agent-nodejs10-angular ... done
oc -n ods start-build jenkins-agent-nodejs10-angualr --follow
build.build.openshift.io/jenkins-agent-nodejs10-angular-3 started
Cloning ...
(some log messages ommited)
error: open /tmp/build/inputs/common/jenkins-agents/nodejs10-angular/docker/Dockerfile.rhel7: no such file or directory.
```

**Additional context**
The rest of Jenkins agent images were installed successfully.

**Comment by michaelsauter** [comment]
Hmm: https://github.com/opendevstack/ods-quickstarters/blob/3.x/common/jenkins-agents/nodejs10-angular/docker/Dockerfile.rhel7.

Did you update Bitbucket?

**Comment by felipecruz91** [comment]
@michaelsauter Just realized that that change was not included as it was pushed a few hours _after_ I started the installation this early morning. I'll try again running the `make install-jenkins-agent` command on Monday.

**Comment by felipecruz91** [comment]
After grabbing that last commit I've re-run `make install-jenkins-agent-nodejs10-angular` and the image has been installed successfully.
