### ISSUE TITLE
Make golang agent buildable on OpenShift installations running in mainland China

### ISSUE THREAD

**Issue by faust2199** [opendevstack/ods-quickstarters#524]
Due to network restrictions, the golang agent fails to build on OpenShift installations running in mainland China. Two issues are blocking the build. Their descriptions and possible solutions are listed below:

1. Unable to download golang binaries from https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz

- Possible solution:
  - Optionally use alternative mirrors to download binaries. Recommendation from golang.org: https://blog.golang.org/hello-china

2. Unable to download golangci-lint installer from https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh

- Possible solutions:
  - Embed the installer script alongside the Dockerfile, so that we can just COPY it to the container instead of downloading it from the Internet. The installer is version agnostic and only changed infrequently (last updated 8 months ago).
  - Obtain the file by "git clone" the repo. The restriction only applies to raw.githubusercontent.com. Other functionalities of GitHub are normal.

**Comment by faust2199** [comment]
Regarding where to download golang binaries, I found that URLs from https://golang.google.cn/dl/ work globally. I tested downloading from servers located in EU and Singapore and speeds were really good. Maybe we don't need to make the URL configurable. We can just use https://golang.google.cn/dl/ everywhere. @michaelsauter Suggestions?

**Comment by michaelsauter** [comment]
@faust2199 haha. https://golang.google.cn/dl/ would work for me. It would be nice to make this configurable, at least within the `Dockerfile` via `ARG`, maybe even up to the `BuildConfig` so that one can easily change it if need be.

About `golangci-lint`, both options work for me. Pick whatever you think works best.
