### ISSUE TITLE
ODS AMI build for master fails due FE ionic quickstarter test failure

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-quickstarters#538]
For some reason, it looks like the fe-ionic is failing due to a failing test. It expect 3 but found 2.

I have check the different repos `ods-core`, `ods-quickstarters` but no changes were done since last successful ODS AMI built. 

This is the reported error:
```
[0;32m    amazon-ebs: Verifying unit tests of run-unitt-fe-ionic-test-unitt-master-1 ...[0m
[0;32m    amazon-ebs:     quickstarter_test.go:346: Expected 3 unit tests, but found only 2 for build:run-unitt-fe-ionic-test-unitt-master-1
``` 

More details in attached log
[fe-ionic-missing-test.txt](https://github.com/opendevstack/ods-core/files/5910867/fe-ionic-missing-test.txt)

**Comment by clemensutschig** [comment]
@stitakis  - moving to ods-quickstarters - it's a quick addition / change in the testdata

**Comment by stitakis** [comment]
@clemensutschig I'll run the test in my odsbox to reproduce... I'll verify how many tests `ionic cli` creates.

At the moment 3 are expected in the test spec (https://github.com/opendevstack/ods-quickstarters/blob/b5416abc267ea2552986721ee18c2acae4dfdfd9/fe-ionic/testdata/steps.yml#L15) but only 2 are found.

> moving to ods-quickstarters - it's a quick addition / change in the testdata
Do you mean to change `3` to `2` to fix this?

**Comment by clemensutschig** [comment]
@stitakis yes - after you verified the CLI ... you can change to `2` tests in steps.yml

**Comment by stitakis** [comment]
@clemensutschig the unit test report for fe-ionic qs shows 2 test... 
![image](https://user-images.githubusercontent.com/1012854/106619658-1b613f80-6571-11eb-920a-ae245cafc869.png)

the fix is simple... however why did ionic cli generate 3 tests in the past and now only 2 tests?

**Comment by clemensutschig** [comment]
Iguess because of a change to the CLI :) which sucks .. but life of dependencies ... :(

**Comment by stitakis** [comment]
I'm investigating if a fix for 3.x is needed

**Comment by stitakis** [comment]
My test of fe-ionic qs for branch 3.x ended successful on my odsbox. Apparently no change is needed in branch `3.x`. I'll close this issue.
