### ISSUE TITLE
revert memory increase for nodejs12 change made on #545

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#547]
**Describe the bug**
There is a clear increase of memory usage but from a clean new provisioned quickstarter the memory is still under the default limits

**Expected behavior**
Revert changes made on #545 

**Screenshots**
Here a pict of a clean fe-angular provisioned quickstarter using nodejs12 agent:
![Screenshot 2021-02-17 at 09 44 45](https://user-images.githubusercontent.com/1785235/108181775-9c3f4000-7108-11eb-9eaf-2dde608a4080.png)

**Affected version (please complete the following information):**
 - OpenShift: 4
 - OpenDevStack master

**Additional context**
This is not a bug per se, but it is good we avoid default/initial memory required for new nodejs12-based quickstarters to using too much memory

**Comment by cschweikert** [comment]
Makes sense. If a component would need more memory, this can still be adjusted on the component's ``Jenkinsfile``.
