### ISSUE TITLE
What about a plain-jenkins-agent qs?

### ISSUE THREAD

**Issue by renedupont** [opendevstack/ods-quickstarters#549]
**Is your feature request related to a problem? Please describe.**
Myself, and I also read from others, had the issue in the past that we needed a custom jenkins-agent image for our pipeline. I know it can be done manually by creating a bitbucket project, add some files, grant permissions, bc in oc ... If you know exactly what to do, it should take less than an hour, but it is still a manual process that requires some background knowledge.

**Describe the solution you'd like**
Analog to the plain-docker component quickstarter, we could provide a plain-jenkins-agent quickstarter. After provisioning, the user would have everything necessary preconfigured and a repo with the plain agent (maybe with a FROM base-agent in the Dockerfile?) and can start adding stuff there that is required for his needs. Also, a small readme with instructions on how to build the image and use it in their component projects could be added.

Do you also see value in this or anything that speaks against it?

**Comment by clemensutschig** [comment]
with the new setup ... (to create the image in the cd namespace - this should be there out of the box)?

**Comment by michaelsauter** [comment]
I think the proposal is about creating custom Jenkins agent images. E.g. you want to use Java 16 but the "ODS official" quickstarter only ships with Java 11. For this you not only need to swap the application image, but also the Jenkins image that executes `./gradlew build`.

> with the new (ods4) setup ... (to create the image in the project's cd namespace

that is for the application images - previously built in foo-dev, now in foo-cd and then transferred.

**Comment by clemensutschig** [comment]
@michaelsauter  - plain docker, built in cd would do it,... because we create the image now in *cd or?

**Comment by renedupont** [comment]
Did I get it right that you basically mean to 
- just provision the plain-docker quickstarter
- add everything necessary into the Dockerfile to be able build the actual application
- also add `FROM jenkins-base-image` to Dockerfile
- remove the deploy stage in the Jenkinsfile
- push it and let the pipeline create the image in the cd namespace
- change in the Jenkinsfile of the actual application the e.g. `imageStreamTag: 'ods/jenkins-agent-maven:3.x',` to `imageStreamTag: '<my_project_namespace>/jenkins-agent-<my_custom_name>:3.x',`
?

**Comment by clemensutschig** [comment]
correct :)

**Comment by renedupont** [comment]
Ok sounds good to me - maybe we could just add then a README.md in the files folder of docker-plain (https://github.com/opendevstack/ods-quickstarters/tree/master/docker-plain/files) that describes this option and the steps mentioned above?

**Comment by renedupont** [comment]
docker-plain has neither a rhel7 and ubi8 Dockerfile nor a ocp-config folder with resources in it like all the actual agents. Are those mandatory?

**Comment by clemensutschig** [comment]
not needed, there is one Dockerfile and the std configs are created ... :) (similar to other quickstarters)
