### ISSUE TITLE
ODS AMI build for master branch is failing due to unbound variable

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-quickstarters#554]
**Describe the bug**
An ODS tests is failing due to a missing variable. 

This is error log:
```
[0;32m    amazon-ebs: + cd /tmp/workspace/unitt-cd/unitt-cd-prov-release-manager-opendevstack-master/release-manager/ocp-configESC[0m
ESC[0;32m    amazon-ebs: + echo 'create trigger secret'ESC[0m
ESC[0;32m    amazon-ebs: create trigger secretESC[0m
ESC[0;32m    amazon-ebs: ++ head /dev/urandomESC[0m
ESC[0;32m    amazon-ebs: ++ tr -dc A-Za-z0-9ESC[0m
ESC[0;32m    amazon-ebs: ++ head -c 13ESC[0m
ESC[0;32m    amazon-ebs: ++ echo ''ESC[0m
ESC[0;32m    amazon-ebs: + SECRET=UN0W6NmQf6S8dESC[0m
ESC[0;32m    amazon-ebs: ./create-ocp-resources.sh: line 45: ODS_BITBUCKET_PROJECT: unbound variable
```

**Comment by stitakis** [comment]
@jssnull It looks like this change broke the build: https://github.com/opendevstack/ods-quickstarters/commit/9adcc6e152a570f1489486001400cd94eb15d99a... can you please have a look?

**Comment by stitakis** [comment]
@jssnull did you have the chance to look at this?

**Comment by jssnull** [comment]
Hi @stitakis  sorry I was with another tasks I'll let you know if I have any updates

**Comment by clemensutschig** [comment]
@jssnull  - you broke master - when do you intend to fix this?!

**Comment by clemensutschig** [comment]
@michaelsauter  - alternatively - can you quickly pick this up?
