### ISSUE TITLE
be-gateway quickstarter

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#56]
**Is your feature request related to a problem? Please describe.**
Since we provide different kind of quickstarters (usually following microservice architecture approach) which usually are dependant between each other, it would be nice to have available an API/Gateway quickstarter that can really handle huge loads and different requirements (e.g.: Nginx).
This is also related to https://github.com/opendevstack/ods-project-quickstarters/issues/424 and 
https://github.com/opendevstack/ods-core/issues/215

**Describe the solution you'd like**
Provide a be-gateway quickstarter with a set of ready-to-use Lua modules for different API/Gateway requirements. This would be using OpenResty.

**Describe alternatives you've considered**
To not provide it --> users will have to use another solution for such requirement

**Additional context**
To proceed by following official images provided --> https://github.com/openresty/docker-openresty

**Comment by tjaeschke** [comment]
I will port the kong gateway quickstarter as soon as we are ready with the specific users tasks

**Comment by gerardcl** [comment]
Hi @tjaeschke ! great!
Let's keep in mind the agreed naming convention: `be-gateway-<tech/provider>`
I am also planning for `be-gateway-nginx` :) not sure if I will be in time for ODS2 though! will try!

**Comment by michaelsauter** [comment]
@gerardcl I think that quickstarter will not make it into ODS 2. Let's target 3 so we can give it some thought.
