### ISSUE TITLE
ds-jupyter-notebook renaming to ds-jupyter-lab

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#562]
**Is your feature request related to a problem? Please describe.**
`ds-jupyter-notebook` is not just a notebook but the Jupyter IDE suite where you are provided not only notebooks, but also terminals. So, I am proposing to renaming it accordingly to `ds-jupyter-lab`.

**Describe the solution you'd like**
To have a fitting name for what this quickstarter provides.

**Describe alternatives you've considered**
Keep it as is.

**Additional context**
If we do not proceed with a proper renaming at least to make it more clear at documentation level.

**Comment by gerardcl** [comment]
FYI @borja44 @metmajer @michaelsauter 
if you all agree I will proceed, this means updating all the refences in the docs and so on, shouldn't be an issue, or?

**Comment by gerardcl** [comment]
@segator @felipecruz91 is this also ok for you? let me know if we should skip this change or any comment! I believe it makes sense now, better later than never! :)

**Comment by felipecruz91** [comment]
@gerardcl I'm happy with any change that makes things clearer 👍

Apart from the documentation, let me gather a few places where the reference should be also changed:

- [ ] ConfigMap `quickstarters.properties`
```
jenkinspipeline.quickstarter.ds-jupyter-notebook.desc=Data Science - Jupyter Notebook
jenkinspipeline.quickstarter.ds-jupyter-notebook.repo=ods-quickstarters
```
- [ ] [Component's metadata.yml](https://github.com/opendevstack/ods-quickstarters/blob/master/ds-jupyter-notebook/files/metadata.yml#L2)
