### ISSUE TITLE
ds-ml-service deprecation - move it to extra-quickstarters

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#568]
**Is your feature request related to a problem? Please describe.**
`ds-ml-service` quickstarter is no longer requested since it has been superseded by other new technologies, like mlflow and other SaaS solutions

**Describe the solution you'd like**
In order to decrease the maintenance load we can move it to extra-quickstarters

**Describe alternatives you've considered**
To keep it

**Additional context**
N/A

FYI @michaelsauter @metmajer @borja44 @hugowschneider @sklingel @clemensutschig 

Let me know if you think we should keep it, otherwise by the end of the week I will provide some PRs

**Comment by michaelsauter** [comment]
I would be in favour of removing it. Note that you'd also need to update the default QS configuration in `ods-core` if we end up removing the QS.

**Comment by gerardcl** [comment]
sure, that is why I said some PRs hehe
when you say "removing" you mean there is no need to move it to extra-quickstarters ? I would also agree

**Comment by michaelsauter** [comment]
ah sorry, meant "removing from this repo, and move to extra-quickstarters" :) I think it would be nice to have it there for the time being.

**Comment by metmajer** [comment]
agree with moving it into extra-quickstarters, as discussed @gerardcl !
