### ISSUE TITLE
latest master (20210505) - ionic QS broken / cli version not found.

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#580]
https://github.com/opendevstack/ods-quickstarters/pull/577 seems to have caused 

```
[0;32m    amazon-ebs: [Pipeline] sh[0m
[0;32m    amazon-ebs: + npm install -g ionic@6.13.1[0m
[0;32m    amazon-ebs: npm ERR! code ETARGET[0m
[0;32m    amazon-ebs: npm ERR! notarget No matching version found for ionic@6.13.1.[0m
[0;32m    amazon-ebs: npm ERR! notarget In most cases you or one of your dependencies are requesting[0m
[0;32m    amazon-ebs: npm ERR! notarget a package version that doesn't exist.[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs: npm ERR! A complete log of this run can be found in:[0m
```

@felipecruz91  - seems like the cli upgrade (did you test that?) fails the buidl now .. please take a  look asap

**Comment by clemensutschig** [comment]
@bljubisic fyi

**Comment by bljubisic** [comment]
I am on it

**Comment by felipecruz91** [comment]
Hi,

Sorry I'm on PTO so I won't be able to do further edits from my phone.

Where does the command `npm install -g ionic@6.13.1` come from?

It should be:

`npm i @ionic/cli@6.13.1`

IIRC, that's what I edited in the PR aforementioned.

**Comment by bljubisic** [comment]
Change is needed in Jenkinsfile, not only in Jenkinsfile.template. Will do the change in a bit and will create PR
