### ISSUE TITLE
Error building the nodejs10-angular Jenkins agent for 3.x

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-quickstarters#593]
**Describe the bug**
The AMI build for ODS 3.x is failing due to a failure in building the `nodejs10-angular` agent.

**To Reproduce**
Go to https://github.com/opendevstack/ods-core/tree/master and see the red badge on top of the `README.md` in the master branch. Download the log file for the 3.x branch at the bottom of the page.

**Affected version (please complete the following information):**
 - OpenDevStack 3.x

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
[0;32m    amazon-ebs: Step 15/19 : RUN npm config set registry=$nexusUrl/repository/npmjs/ &&     npm config set always-auth=true &&     npm config set _auth=$(echo -n $nexusAuth | base64) &&     npm config set email=no-reply@opendevstack.org &&     npm config set ca=null &&     npm config set strict-ssl=false &&     yarn config set registry $nexusUrl/repository/npmjs/ -g &&     npm install -g @angular/cli@8.0.1 --unsafe-perm=true --allow-root &&     npm install -g cypress@3.3.1 --unsafe-perm=true --allow-root > /dev/null &&     npm --version &&     ng version &&     cypress verify[0m
[0;32m    amazon-ebs:  ---> Running in 4df9f4e25549[0m
[0;32m    amazon-ebs: [91m/usr/local/bin/scl_enable: line 3: scl_source: No such file or directory[0m
[0;32m    amazon-ebs: [0myarn config v1.22.5[0m
[0;32m    amazon-ebs: success Set "registry" to "https://nexus-ods.ocp.odsbox.lan/repository/npmjs/".[0m
[0;32m    amazon-ebs: Done in 0.04s.[0m
[0;32m    amazon-ebs: [91mnpm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue[0m
[0;32m    amazon-ebs: [0m[91mnpm ERR! code E404[0m
[0;32m    amazon-ebs: [0m[91mnpm ERR! 404 Not Found - GET https://nexus-ods.ocp.odsbox.lan/repository/npmjs/aproba/-/aproba-1.2.0.tgz[0m
[0;32m    amazon-ebs: npm [0m[91mERR! 404[0m
[0;32m    amazon-ebs: npm ERR![0m[91m 404  'aproba@^1.1.1' is not in the npm registry.[0m
[0;32m    amazon-ebs: [0m[91mnpm[0m[91m ERR![0m[91m 404[0m[91m You should bug the author to publish it (or use the name yourself!)[0m
[0;32m    amazon-ebs: npm ERR! [0m[91m404 It was specified as a dependency of 'move-concurrently'[0m
[0;32m    amazon-ebs: npm ERR! 404[0m
[0;32m    amazon-ebs: npm ERR! 404[0m[91m Note that you can also install from a[0m
[0;32m    amazon-ebs: npm[0m[91m ERR! 404 tarball, folder, http url, or git url.[0m
[0;32m    amazon-ebs: [0m[91m[0m
[0;32m    amazon-ebs: npm ERR![0m[91m A complete log of this run can be found in:[0m
[0;32m    amazon-ebs: npm ERR!     /home/jenkins/.npm/_logs/2021-05-28T00_51_48_027Z-debug.log[0m
[0;32m    amazon-ebs: [0mRemoving intermediate container 4df9f4e25549[0m
[0;32m    amazon-ebs: error: build error: The command '/bin/bash -o pipefail -c npm config set registry=$nexusUrl/repository/npmjs/ &&     npm config set always-auth=true &&     npm config set _auth=$(echo -n $nexusAuth | base64) &&     npm config set email=no-...
```

FYI @clemensutschig @michaelsauter @stitakis

**Comment by michaelsauter** [comment]
Is this also the case for `master`?

AFAICT, `'aproba@^1.1.1' is not in the npm registry` is the issue, and as that dependency is not mentioned explicitly in this repo, it must be the dependency of some other package. @bljubisic @cschweikert @ManuelFeller would you have time to investigate?

**Comment by clemensutschig** [comment]
actually I think we should remove it ... (@michaelsauter - what will tailor do, if we remove the bc / is here? ) - I would like to pre-serve it in case you have already installed it.

**Comment by michaelsauter** [comment]
3.x provides 10, master/4.x provides 12. I think for 3.x we need to keep 10 for backwards compatibility.

@clemensutschig as long as it does not have the same label tailor will not touch it.

**Comment by ManuelFeller** [comment]
After a quick search I can say that the Package exists: <https://www.npmjs.com/package/aproba/v/1.1.1>

As we had this quite a few times in the past: how is that nexus configured? Very often invalidating the cache solved issues of that type - if for some network hiccup the request from nexus fails it remembers this by default for at least a day and does not recheck.
So my first question to @metmajer would be: Does this still happen or does it work now when you trigger a new build?

And did anyone set nexus to re-check basically every minute (**important: do not set it to 0, that would mean it never re-checks!**) - or is it still on the default settings (or even worse set to 0)?

**Comment by ManuelFeller** [comment]
@michaelsauter we could burden us with a huge amount of fixing issues outside of our normal responsibility if we really go this route. I will open another issue to start a discussion how to deal with that topic...

**Comment by michaelsauter** [comment]
The error went away but we have a new, related issue: #595

**Comment by ManuelFeller** [comment]
As subsequent builds did not fail with the same issue and the causing package is clearly available in the npmjs repository it was most likely a nexus hiccup as mentioned above.

We have that issue once every few month too; as said at that time you need to invalidate the cache or wait until it invalidates itself. That is why we run with one minute package re-validation time, so no one needs to bother an admin to do so.
