### ISSUE TITLE
Spring Boot quickstarter ignores property no_nexus

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-quickstarters#61]
**Describe the bug**
According to https://www.opendevstack.org/ods-documentation/ods-project-quickstarters/latest/be-java-springboot.html, it is possible to build the generated code without using nexus, by creating the `gradle.properties` file with content `no_nexus=true`.

**Expected behavior**
Local gradle build succeds without error.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 2

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
D:\projekte\ods\demo\local\tst10-bespringboot>gradlew build
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Failed to notify dependency resolution listener.
   > Could not resolve all dependencies for configuration ':detachedConfiguration1'.
      > Authentication scheme 'all'(Authentication) is not supported by protocol 'file'
   > Could not resolve all dependencies for configuration ':detachedConfiguration2'.
      > Authentication scheme 'all'(Authentication) is not supported by protocol 'file'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Additional context**

**Comment by stefanlack** [comment]
Reason for bug: new build.gradle is not the same than old one.

**Comment by michaelsauter** [comment]
@stefanlack Hmm, yea it looks like the new version is different than the old one. But I don't know why. Looks like a bug to me - the "old" version looks correct in my eyes.

**Comment by stefanlack** [comment]
@michaelsauter  np problem for me. Bugfix is in testing. I will create a pr soon.
