### ISSUE TITLE
Scala Jenkins agent runtime error in OCP4

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-quickstarters#610]
**Describe the bug**
When running the Scala Jenkins agent in OCP4, the container starts and fails immediately after a `FileNotFoundException` error, entering in a fail loop forever.

**To Reproduce**
1. Add a Scala Quickstarter to your project.
2. Check the Jenkins build log.
3. See error

**Expected behavior**
To have a successful build of the Scala Jenkins agent in OCP4.

**Screenshots**
![image](https://user-images.githubusercontent.com/15997951/123826279-eaa6eb80-d8ff-11eb-87e5-7f2765e8874e.png)

**Affected version (please complete the following information):**
 - OpenShift: 4.7
 - OpenDevStack (master, git commit 431e4c250b4)
**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
Log output here...
```

**Additional context**

cc/ @oalyman

**Comment by clemensutschig** [comment]
how come this is working in the CI?

**Comment by clemensutschig** [comment]
Thats super weird..  really... we can set it to r+w

**Comment by clemensutschig** [comment]
Do you See the same with spring/gradle? 

I guess in the ubi Images the keystore rights changed
