### ISSUE TITLE
be-gateway-nginx switch from centos

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#611]
**Is your feature request related to a problem? Please describe.**
We are currently using centos7 base image for the be-gateway-nginx quickstarter. Since centos is not not any longer maintained, and althought the current quickstarter works, we will face obvious issues soon and also some issues might happen already when trying to update the repos or adding other packages for example.

**Describe the solution you'd like**
We can just switch to fedora since that is also now what the openresty project has done and is providing as base image.

**Describe alternatives you've considered**
Keep current centos7 or switch to a full different distro.

**Additional context**
N/A

**Comment by michaelsauter** [comment]
Is there an easy way to use a UBI base image?

**Comment by gerardcl** [comment]
I can take a look on the dockerfile openresty uses and try exchanging with an UBI base one but I would fire another issue for that, shall we?

AFAIK there is an nginx UBI base image already so maybe we could even benefit from that one and just compile missing pieces...not sure, have to check!

**Comment by gerardcl** [comment]
so basically, if the Dockerfile gets too big or "not nice" we could have a base image from an ODS core point of view maybe, what do you think? I guess that could be one of the ways to solve this centralisation of patch management also...

**Comment by michaelsauter** [comment]
I'd avoid another layer. What would this shared base image contain? I am rather in favour of small, specialised images - now with OpenShift 4 we can also make more use of build stages producing images which only contain the really necessary stuff.

**Comment by gerardcl** [comment]
did not know! cool! so, here my thoughts -> shouldn't that be targetted once we don't support OpenShift 3.11 anymore? Maybe for ODS3 and 4 we can keep current state and once we start targetting ODS5 we jump into this OpenShift4 feature?

**Comment by gerardcl** [comment]
@michaelsauter  I have closed the issue via the merge of the related PR, we can continue the discussion though :)
