### ISSUE TITLE
Scala agent build fail, it is forbidden to download sbt-1.3.13.rpm

### ISSUE THREAD

**Issue by jorge-romero** [opendevstack/ods-quickstarters#619]
**Describe the bug**
Building the scala agent fails when it tries to download sbt rpms.

If you try to download the rpm as it is done in the quickstarter 'curl -O -L http://dl.bintray.com/sbt/rpm/sbt-$SBT_VERSION.rpm' it fails as it is forbidden to download the file.

**To Reproduce**
1. Rebuild the scala agent.
2. Build will fail, and if you check the downloaded file it will contain "Forbiden"

**Expected behavior**
The image is built

**Affected version (please complete the following information):**
 - OpenShift: [ALL]
 - OpenDevStack [ALL]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
Step 8/19 : RUN curl -O -L http://dl.bintray.com/sbt/rpm/sbt-$SBT_VERSION.rpm  &&     yum -y install sbt-$SBT_VERSION.rpm &&     yum clean all &&     rm -rf /var/cache/yum
 ---> Running in 4120d8ef5e99
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100    10  100    10    0     0    151      0 --:--:-- --:--:-- --:--:--   153
Loaded plugins: fastestmirror, ovl
Cannot open: sbt-1.3.13.rpm. Skipping.
```

**Comment by jorge-romero** [comment]
@michaelsauter could you have a look at that or point it to the right person.

**Comment by michaelsauter** [comment]
@oalyman Could you have a look?

**Comment by oalyman** [comment]
@jorge-romero @michaelsauter There seems to be no bintray anymore... https://jfrog.com/center-sunset/
I will check for the current right way to install sbt and update the agent
