### ISSUE TITLE
R-shiny quickstarter failed to build

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#627]
**Describe the bug**
The build of the R-shiny quickstarter is falling to build the image from the dockerfile available in GH from the master branch

**To Reproduce**
1. Create a new OD project
2. Add the R-shiny quickstarter
3. The Openshift build stage will fail

**Expected behavior**
That the Openshift build stage works

**Screenshots**
![image](https://user-images.githubusercontent.com/26645694/125908601-1e4c4682-1fd4-43c1-977a-5ab084a25328.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
--
  | ---> Running in c4071caf6b0f
  |  
  | Warning: apt-key output should not be parsed (stdout is not a terminal)
  | Executing: /tmp/apt-key-gpghome.woFugLUDbB/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  | gpg: keyserver receive failed: End of file
  | Removing intermediate container c4071caf6b0f
  | error: build error: The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9' returned a non-zero code: 2

```

**Additional context**
The error seems to come from here: https://github.com/opendevstack/ods-quickstarters/blob/master/ds-rshiny/files/docker/Dockerfile#L24

@felipecruz91 @jssnull

**Comment by felipecruz91** [comment]
I tried building the image in my local and I get the same error

**Comment by braisvq1996** [comment]
Great @felipecruz91, with that flag the Openshift build does work.

**Comment by felipecruz91** [comment]
@michaelsauter Is it OK to create a PR with the change aforementioned?

**Comment by gerardcl** [comment]
did you also try to enable the proxy at image level? with export HTTP_PROXY and so on?

**Comment by braisvq1996** [comment]
@gerardcl - We already make use of the proxy as environment variables when building the images:
![image](https://user-images.githubusercontent.com/26645694/126111779-633b360e-eb91-4b68-a747-e28056f001b3.png)

**Comment by gerardcl** [comment]
> I tried building the image on my corporate laptop and I get the same error. However, on my personal laptop, it builds successfully.
> 
> I believe then this has to do with some corporate firewall rules blocking the connection.
> 
> Passing the flag `--keyserver-options http-proxy=your-corporate-proxy` does the trick.

@felipecruz91 does that handles empty/no proxy? or you would need two different commands within a met condition?

**Comment by braisvq1996** [comment]
@gerardcl , I think that it is not able to handle empty values.
Maybe we can have an if statement to check if the proxy is set as an environment value?
