### ISSUE TITLE
Azure Quickstarter

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-quickstarters#628]
**Is your feature request related to a problem? Please describe.**
Today an AWS Quickstarter is included. Most users utilize additional cloud providers like GCP, Azure or Alibaba.

**Describe the solution you'd like**
ODS-Quickstarters should support Azure as an additional cloud provider (others could follow).

**Describe alternatives you've considered**
Using the baseline of  inf-terraform-aws quickstarter still requires some adoptions for an Azure quickstarter.

**Additional context**
If terraform is kept as cloud infrastructure tooling also for Azure (quick win) then the following adoptions are needed starting with inf-terraform-aws:
- credentials mapping
- use inspec-azure instead of inspec-aws
- different code sample in main.tf
- add Azure specific gems and pip packages
- terraform provider settings
- terraform backend definition

**Comment by metmajer** [comment]
Hmm....

**Comment by gerardcl** [comment]
Hi!

I have been thinking about the current approach, here a thought: if we are mainly targetting using terraform for infrastructure as code (as in the inf-aws-terraform), why don't we just target to be even more generic up to "inf-terraform"?

**Comment by metmajer** [comment]
Apologies @tbugfinder @nichtraunzer, if it appears as if there was low interest on my end. In fact, I got disrupted but somehow managed to still send my comment.

Anyway, the Azure Quickstarter was highly awaited. Thanks for taking the initiative. I would like to ensure that the team who owns the service also has a good understanding of the Quickstarter, so please make this a (scalable) team effort.

@gerardcl the downside of a `inf-terraform` is that this would make it impossible to pre-configure the Quickstarter to be used immediately for a specific Cloud provider.

**Comment by gerardcl** [comment]
hi @metmajer, 
keeping the discussion of a generic terraform quickstarter and based on your last comment -> since terraform is based on providers and one can easily modularise (so reuse and so on) any resource/component context, wouldn't it make sense to provide those as terraform modules maybe? so one could select whatever module to use based on the provider?

this is also food for thoughts for you @nichtraunzer  and @tbugfinder

**Comment by tbugfinder** [comment]
Hi @gerardcl , a generic terraform quickstarter sounds reasonable however it quickly gets (cloud) provider agnostic. So it depends on what a quickstarter should really provide and which additional modules ODS space would provide.
It even sounds like the contrary edge case was just mentioned in https://github.com/opendevstack/ods-quickstarters/issues/631 with even having a quickstarter ready for a cloud provider's service definition.

**Comment by gerardcl** [comment]
Hi @tbugfinder , I totally agree with all you've mentioned and also in the issue related, I understand the points and all goes in the same direction, which I think is of trying to provide the rightest customer experience and also maintenance experience AFAIK.
Having said that, the approach I am suggesting is to go more on the direction of providing a solution that focuses more on the technology provided rather than encapsulating it on top of another library. But maybe you see other issues I might not see? just want to be aligned with you and open such discussions since I want to be a user of this too :)

**Comment by nichtraunzer** [comment]
hi @gerardcl, though i fully agree with @tbugfinder I see your point here, too. Maybe this is a good opportunity to discuss this topic in one of our upcoming touch point sessions I scheduled today.

**Comment by tbugfinder** [comment]
Would it be a valid approach to have a terraform quickstarter without following provider specifications:
```
- no credentials mapping
- no inspec-azure or inspec-aws or inspec-*
- no sample code in main.tf
- no cloud provider specific gems and pip packages
- only general terraform version / provider settings
- no terraform backend definition (as it might vary per cloud provider)
```

Based on the slim-terraform-quickstarter the provisioning would provide a "cloud" provider selection (azure/aws/both/...) and walk through a merging phase so that either choice will be provisioned into the target repository.

Would you such still consider being a definition of a Quickstarter?

**Comment by gerardcl** [comment]
hi @tbugfinder ! 

I think I need to understand more the current approach. Looking forward for the next session!

Nevertheless, I am just trying to challenge the concept based on what I have experienced so far. Happy to keep the discussion and maybe providing some help!

**Comment by metmajer** [comment]
@tbugfinder @gerardcl in all fairness, I would not know how much a "Quickstarter" makes sense if a user would have to wire so much tooling, including testing frameworks again? The beauty of a Quickstarter is that such wiring and usage examples are included.

**Comment by tbugfinder** [comment]
I don't think the question is about moving customization down to the user, but rather duplicate and maintain as less code as possible. AWS and Azure QS share a baseline.
A PR will show differences between AWS and Azure which are rather minimal.
Maybe a helper like [cookiecutter](https://github.com/cookiecutter/cookiecutter) could merge what's needed when provisioning app creates an instance of the Quickstarter.

**Comment by gerardcl** [comment]
@tbugfinder see the discussion going on here too https://github.com/opendevstack/ods-quickstarters/issues/631
