### ISSUE TITLE
openshift template v1 annotation depcreation

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#639]
**Describe the bug**
OpenShift templates are deprecating `v1` in favour of `template.openshift.io/v1`.

**To Reproduce**
1. Deploy a quickstarter (e.g.: be-java-springboot)
2. Go to the master branch pipeline
3. See warning

**Expected behavior**
We should handle such deprection warning

**Affected version (please complete the following information):**
 - OpenShift: 4
 - OpenDevStack all

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
warning states:
W0728 08:08:03.166356 3571 shim_kubectl.go:55] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "template.openshift.io/v1" for your resource
```

**Additional context**
This might impact current ods-pipeline implementations maybe? @michaelsauter  @felipecruz91

**Comment by michaelsauter** [comment]
@gerardcl thanks for the heads up! It does not affect `ods-pipeline` though as `ods-pipeline` targets Kubernetes, not OpenShift exclusively. Therefore we do not make use of any OpenShift-only functionality such as OpenShift templates. All manifest templating in `ods-pipeline` is based on Helm, which works with plain Kubernetes but can also create OpenShift-specific resources now such as routes and build configs.

**Comment by gerardcl** [comment]
@michaelsauter shall we add this to 4.x?
