### ISSUE TITLE
Use Java 17 (LTS) in maven jenkins-agent and spring boot quickstarter

### ISSUE THREAD

**Issue by renedupont** [opendevstack/ods-quickstarters#651]
Java 17 has been released a couple of months ago. Since it is an LTS version, it might make sense to use it. Currently we are at Java 11. 
Once we on it, we could also update gradle in the spring boot quickstarter, we are 3 major versions behind.

Any reason what would speak against it? Too early?

**Comment by renedupont** [comment]
@metmajer yes makes sense, that's what I "feared" 😄 

@stitakis I was also refering to the (maven) agent which does
`FROM opendevstackorg/ods-jenkins-agent-base-ubi8:latest`
and then adds java 11 (https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/maven/docker/Dockerfile.ubi8)
without the agent being on 17 we can't build them on it.

**Comment by metmajer** [comment]
@stitakis if you do not wait, it means that the owners of this quickstarter will have more work sorting out security incidents themselves vs. being supported by a vendor.

**Comment by renedupont** [comment]
@stitakis just to clarify, you meant regarding eclipse-temurin not the new official open jdk source, but rather new **adopt** open jdk, right?

**Comment by metmajer** [comment]
@stitakis what about you make the Quickstarter with jdk 17 available on a feature branch that you release into the BIX cluster and leave both master and 4.x intact? Just to clarify, with security scanning being activated on all new clusters, we want to reduce the likelihood for vulnerabilities. The best way to keep the house clean seems to be that all quickstarters are based on a common, secure foundation. Not all quickstarteres are there yet, but we need to get there very soon.

**Comment by stitakis** [comment]
@metmajer ok, I see... it looks to early to upgrade to jdk 17 based on an ubi image

**Comment by renedupont** [comment]
> @renedupont but, does it need to be on the same jdk version? btw... I can't remember, why maven is needed to be installed in the agent?

Correct me if I'm wrong, but if you write your app in Java 17 but try to build it with an agent that only has Java 11 installed, it will fail.

**Comment by stitakis** [comment]
@kuebler @renedupont I have merged this to master. I'll port this feature to 4.x
