### ISSUE TITLE
inf-terraform-aws - stage smoke should be named "Smoke - Test"

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-quickstarters#655]
inf-terraform-aws - stage smoke should be named "Smoke - Test" or "SmokeTest".

https://github.com/opendevstack/ods-quickstarters/blob/aafa5b3db91a72f30b5c4111d557ffe1cbbadba8/inf-terraform-aws/Jenkinsfile.template#L146

**Comment by tbugfinder** [comment]
Validation might be a reserved term.

**Comment by metmajer** [comment]
Deployment Tests are a standard term. In the book continuous delivery, smoke tests are named as an alternative name.

**Comment by gerardcl** [comment]
I would vote for "deployment tests" since it is the one clearer to me on what is that stage doing

**Comment by nichtraunzer** [comment]
will be covered by [#740](https://github.com/opendevstack/ods-jenkins-shared-library/pull/740)
