### ISSUE TITLE
security issue in ds-jupyter qs related to vulnerable nltk dependency

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-quickstarters#676]
github dependabot reported a security issue in ds-jupyter-lab quickstarter
https://github.com/opendevstack/ods-quickstarters/security/dependabot/ds-jupyter-lab/files/docker/requirements.txt/nltk/open

**Comment by stitakis** [comment]
@gerardcl we are creating an issue for the dependabot reported findings and asking the quickstarter owner to review. Could you please have a look at this one? Thanks

**Comment by gerardcl** [comment]
hi @stitakis , as per the dependabot message, one just needs to upgrade the version, it won't affect anything else, we could even remove that package if really an issue. Nevertheless, I don't see it really being a critial or high vulnerability as per the way that lib can be used.

**Comment by stitakis** [comment]
thanks for the feedback. The dependabot offer the "dismiss" button to disable the finding for cases where the finding is not applicable and other cases. It sound to be that this could be the case. The fix sounds easy, would you provide the upgrade or prefer to dismiss the finding?

**Comment by gerardcl** [comment]
closing this issue, see https://github.com/opendevstack/ods-quickstarters/pull/678
