### ISSUE TITLE
security issue in inf-terraform quickstarter related to vulnerable addresable dependency

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-quickstarters#677]
github dependabot reported following security issues related to
-  inf-terraform quickstarter:
https://github.com/opendevstack/ods-quickstarters/security/dependabot/inf-terraform-aws/files/Gemfile.lock/addressable/open

- and the corresponding jenkins agent
https://github.com/opendevstack/ods-quickstarters/security/dependabot/common/jenkins-agents/terraform/docker/Gemfile.lock/addressable/open

**Comment by stitakis** [comment]
@frankjoas @metmajer @nichtraunzer @tbugfinder we are creating an issue for the dependabot reported findings and asking the quickstarter owner to review. Could you please have a look at this one? Thanks!

**Comment by nichtraunzer** [comment]
are provided links supposed to work ?

**Comment by metmajer** [comment]
@nichtraunzer they are working for me:

<img width="1116" alt="Screenshot 2021-11-25 at 11 44 00" src="https://user-images.githubusercontent.com/873565/143427237-c26f2e21-57f5-438a-9b63-98a6b2aea7df.png">

**Comment by nichtraunzer** [comment]
Thanks @metmajer - I guess I am lacking some access rights. 
@stitakis : is that needed for the current 4.x / 1.2 release ? no version has been specified in the issue

**Comment by stitakis** [comment]
The dependabot doesn't specify the affected branch. Please coordinate with @metmajer for providing a fix for 4.x

**Comment by tbugfinder** [comment]
> Thanks @metmajer - I guess I am lacking some access rights.
> @stitakis : is that needed for the current 4.x / 1.2 release ? no version has been specified in the issue

I also get 404 when trying to access the links.

**Comment by tbugfinder** [comment]
Overall we discussed to bump several versions within the QS.

- cinc-auditor => 4.52.9
- inspec-aws => 1.80.0
- kitchen-terraform => 6.1.0 (primary target to fix this issue)
- terraform version => 1.0.11
- rebuild Gemfile (.lock)
- ruby 2.7.5 (opt)
- pre-commit-hooks (versions, add python checks (opt.))
- Pipfile
