### ISSUE TITLE
AWS Quickstarter: reports/installed directory missing 

### ISSUE THREAD

**Issue by nichtraunzer** [opendevstack/ods-quickstarters#679]
When deploying the QS with the prov app the reports/install directory will not be deployed though it is part of the quickstarters files directory.

reports/install is used to keep some temporary files for the document creation.

it seems we run into some sort of chicken egg issue because though there is a .gitkeep in this directory reports/install itself is mentioned in the .gitignore file as well.

**Affected version :**
 - aws quickstarter [4.x]

**Comment by michaelsauter** [comment]
Hehe, I think you are looking for this: https://stackoverflow.com/questions/4250063/how-to-gitignore-all-files-folder-in-a-folder-but-not-the-folder-itself :)

**Comment by nichtraunzer** [comment]
exactly - found this too https://medium.com/@kinduff/hey-git-please-keep-those-folders-eb0ed37621c8
