### ISSUE TITLE
DocGen resoures configuration issue

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#681]
**Describe the bug**
Currently DocGen has [512MB as resoureces limit](https://github.com/opendevstack/ods-quickstarters/blob/master/release-manager/ocp-config/cd-docgen.yml#L21) and java is set to [xmx 512m](https://github.com/opendevstack/ods-quickstarters/blob/master/release-manager/ocp-config/cd-docgen.yml#L27) also, this may cause problemes as there is not only java running in the container, like wkhtmltopdf.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 4.x

**Log Output**
```
[ERROR]: [wkhtmltopdf, --encoding, UTF-8, --no-outline, --print-media-type, --enable-local-file-access, -T, 40, -R, 25, -B, 25, -L, 25, --header-center, Overall Technical Installation Report, Config Item: XXXXXX
Doc ID/Version: see auto-generated cover page, --header-font-size, 10, --header-spacing, 10, --footer-center, 'Page [page] of [topage]', --footer-font-size, 10, /tmp/Overall-TIR-Cover-v1.28476040490903818232/templates/Overall-TIR-Cover.html, /tmp/document469614691320331772.pdf] has exited with code 137
```

**Additional context**
For now the easy fix is to increase manually the resources limits of Docgen container a bit (784 MB was fine)

@s2oBCN @jafarre-viewnext

**Comment by victorpablosceruelo** [comment]
We are suffering from this issue right now id EdpBoxes, at least in branches master, 4.0 and experimental.
@jafarre-viewnext @braisvq1996 , when @braisvq1996 says it is enough with 784 MB for container, is it ok with xmx 512 or we should increase the other one too?
Thanks !!!

**Comment by jafarre-viewnext** [comment]
Resource limit - max heap = guarranted minimum available memory for other processes, such as wkhtmltopdf.
The current situation: resource limit and max heap are both 512 MB, so 512-512=0Mb available in the worst case.
Setting resource limit to 764 leaves a guarranted 256Mb of memory. Note that these 256Mb of memory are shared by wkhtmltopdf, the operating system, the metaspace, the java process itself and anything which is not inside the java heap.
I would say, to be on the safe side, a resource limit of 1024Mb is safer.
The max heap should not be increased, unless you are getting OutOfMemoryError's, but always remember to leave free memory for other things.

**Comment by victorpablosceruelo** [comment]
We should include the modification of docgen pod maximum memory as a change for a future release.
Right now I think we can live modifying by hand the resource limit in OCP3.

To have better results when searching for this problem, I include here my trace too:

```
java.lang.RuntimeException: Error: unable to create document 'Overall-TIR-Cover (v1.2)'. 
DocGen responded with code: '500' and message: 
'{"message":
"PDF Creation of /tmp/Overall-TIR-Cover-v1.25902772205841795455/templates/Overall-TIR-Cover.html failed!\r:

Loading pages (1/6)\n
[&gt;                                                           ] 0%\r
[======&gt;                                                     ] 10%\r
[==============================&gt;                             ] 50%\r

\r:Error code:137",

"stacktrace":["java.lang.IllegalStateException: PDF Creation of 
/tmp/Overall-TIR-Cover-v1.25902772205841795455/templates/Overall-TIR-Cover.html failed!:

Loading pages (1/6)",
"[>                                                           ] 0%
[======>                                                     ] 10%
[==============================>                             ] 50%:

Error code:137",

"\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)",
"\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)",
"\tat ...
```

**Comment by victorpablosceruelo** [comment]
The change needed to overcome the problem:

![image](https://user-images.githubusercontent.com/1253881/177494797-426e88c5-d4e3-49ff-9f50-78ab528c3d6f.png)

**Comment by victorpablosceruelo** [comment]
The place where we have to modify the value so the boxes get the correct memory limit for the pod is:

https://github.com/opendevstack/ods-quickstarters/blob/master/release-manager/ocp-config/cd-docgen.yml
