### ISSUE TITLE
maven agent does not support HTTPS proxy

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#689]
**Describe the bug**
today only http proxy is supported - this is a huge limitation in a corporate network (and when people need to go out for non nexus repos)

https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/maven/docker/set_maven_proxy.sh

**Comment by stitakis** [comment]
@clemensutschig 
It looks like the current implementation was close to support `https` but somehow was not added.

I guess this could be fixed by changing the corresponding code in `set_maven_proxy.sh` by these lines:
```
mvn_proxy="<proxy><id>internal</id><active>true</active>"

	protocol=$(echo $HTTP_PROXY | sed -e "s|https://||g" | sed -e "s|http://||g")
        mvn_proxy=$mvn_proxy"<protocol>$protocol</protocol>"

...
```

**Comment by clemensutschig** [comment]
@stitakis  - indeed - see PR :)

**Comment by stitakis** [comment]
reopened because we need to port this to branch `4.x`
