### ISSUE TITLE
Airflow requires NEXUS_HOST in custom-create-component.sh but does not use it

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#70]
We should be able to just remove that param?

**Comment by michaelsauter** [comment]
Actually, same for ds-ml-service ...

**Comment by gerardcl** [comment]
both services might require being able to have access to nexus:
- airflow -> for specific DAGs jobs (for example)
- ds-ml-service -> remote training (for example)

anyway, if this is really required to be removed then we can document that if this is later on required users can add it manually

I will do a another check though an come back to this ticket

@hugowschneider @sklingel  please share your thoughts here too, thanks!

**Comment by michaelsauter** [comment]
See https://github.com/opendevstack/ods-quickstarters/blob/master/be-airflow/custom-create-components.sh ... it does not seem to use `NEXUS_HOST` at all ...

**Comment by gerardcl** [comment]
I've looking into it, conclusion: I will clean up `NEXUS_HOST` --> if really required then users can make use of it anyway.

**Comment by gerardcl** [comment]
@michaelsauter  the second commit of the PR in place is cleaning up NEXUS_HOST in all other quickstarters too, since there is no longer used either. Shall we change this issue title then?
