### ISSUE TITLE
Docker build fails on 4.x branch

### ISSUE THREAD

**Issue by jchaves** [opendevstack/ods-quickstarters#704]
https://github.com/opendevstack/ods-quickstarters/blob/86ff3d26401486da6e9aed05aaa956ccb9421a5d/common/jenkins-agents/maven/docker/Dockerfile.centos7#L31

```
No package epel-release available.

 Error: Not tolerating missing names on install, stopping.
 Removing intermediate container 5cba03ba480c
 error: build error: The command '/bin/bash -o pipefail -c yum install -y epel-release && yum repolist && yum install -y java-17-openjdk-devel java-17-openjdk-jmods java-11-openjdk-devel java-11-openjdk-jmods &&     yum clean all -y && rm -rf /var/cache/yum &&     chmod ug+x /home/jenkins/use-j17.sh &&     chmod ug+x /home/jenkins/use-j11.sh &&     /home/jenkins/use-j17.sh &&     /home/jenkins/use-j11.sh &&     echo $JAVA_HOME' returned a non-zero code: 1
```

```
No package java-11-openjdk-jmods available.

 Error: Not tolerating missing names on install, stopping.
 Removing intermediate container a7658e957d7d
 error: build error: The command '/bin/bash -o pipefail -c yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm  && yum repolist && yum install -y java-17-openjdk-devel java-17-openjdk-jmods java-11-openjdk-devel java-11-openjdk-jmods &&     yum clean all -y && rm -rf /var/cache/yum &&     chmod ug+x /home/jenkins/use-j17.sh &&     chmod ug+x /home/jenkins/use-j11.sh &&     /home/jenkins/use-j17.sh &&     /home/jenkins/use-j11.sh &&     echo $JAVA_HOME' returned a non-zero code: 1
```

After making a couple modifications, we got it to build:

`RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum repolist && yum install -y java-17-openjdk-devel java-17-openjdk-jmods java-11-openjdk-devel java-11-openjdk-jmods  && \`

However, this leaves the package java-11-openjdk-jmods uninstalled, we still have to check why the package is not found.

**Comment by stitakis** [comment]
@jchaves I'm not sure if we need this package for java 11. I'd say, we should remove it if we don't find a reason.

**Comment by jchaves** [comment]
@stitakis honestly, I have no idea either. I'm definitely not a java dev, so I'm not even sure what this "jmods" would do _(a quick search tells me that it " is intended for modules that have native libraries or other configuration files", but I'm not savvy enough to really understand that :)

The thing is: the package exists (or seems to; https://centos.pkgs.org/7/centos-x86_64/java-11-openjdk-jmods-11.0.8.10-1.el7.x86_64.rpm.html for example), so I'm not sure why it is not installing. Maybe it was removed from some official repos or something?

I guess I'll let you guys decide which path to take in order to solve the situation

**Comment by stitakis** [comment]
@braisvq1996 in that case, let us close this issue. We can always reopen it if is not the case.
