### ISSUE TITLE
Jenkins Agent AWS Terraform image build fails on old python version

### ISSUE THREAD

**Issue by cschweikert** [opendevstack/ods-quickstarters#707]
**Describe the bug**
Jenkins Agent AWS Terraform image build fails while complaining about needing python 3.7 instead of 3.6.

**To Reproduce**
1. Do an `oc login` and `oc project ods`
2. Go to `ods-quickstarters`, e.g. with latest `4.x` branch
3. Run `make apply-jenkins-agent-terraform-build`

**Expected behavior**
According to line `ENV PYTHON_VERSION 3.7.10` I'd expect pyhton version 3.7.10 to be installed.

**Screenshots**

**Affected version:**
 - OpenDevStack 4.x

**Log Output:**
```
[...]

+ dnf -y install yum-utils gcc make git-core zlib zlib-devel gcc-c++ patch readline readline-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison curl sqlite-devel xz
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

CentOS-8-BaseOS                                  34 MB/s |  20 MB     00:00    
CentOS-8-AppStream                               47 MB/s |  19 MB     00:00    
Red Hat Universal Base Image 8 (RPMs) - BaseOS  6.4 MB/s | 796 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - AppStre  25 MB/s | 2.6 MB     00:00    
Red Hat Universal Base Image 8 (RPMs) - CodeRea 202 kB/s |  16 kB     00:00    
Package make-1:4.2.1-11.el8.x86_64 is already installed.
Package git-core-2.27.0-1.el8.x86_64 is already installed.
Package zlib-1.2.11-17.el8.x86_64 is already installed.
Package readline-7.0-10.el8.x86_64 is already installed.
Package bzip2-1.0.6-26.el8.x86_64 is already installed.
Package curl-7.61.1-18.el8_4.2.x86_64 is already installed.
Dependencies resolved.
================================================================================
 Package                   Arch    Version              Repository         Size
================================================================================
Installing:
 autoconf                  noarch  2.69-29.el8          centos-baseos     710 k
 automake                  noarch  1.16.1-7.el8         centos-baseos     713 k
 bison                     x86_64  3.0.4-10.el8         centos-baseos     688 k
 gcc                       x86_64  8.5.0-10.el8         centos-baseos      23 M
 gcc-c++                   x86_64  8.5.0-10.el8         centos-baseos      12 M
 libffi-devel              x86_64  3.1-23.el8           centos-appstream   29 k
 libtool                   x86_64  2.4.6-25.el8         centos-baseos     709 k
 openssl-devel             x86_64  1:1.1.1k-5.el8_5     centos-appstream  2.3 M
 patch                     x86_64  2.7.6-11.el8         centos-appstream  138 k
 readline-devel            x86_64  7.0-10.el8           centos-appstream  204 k
 sqlite-devel              x86_64  3.26.0-15.el8        centos-appstream  165 k
 xz                        x86_64  5.2.4-3.el8          centos-appstream  153 k
 yum-utils                 noarch  4.0.21-10.el8        centos-appstream   73 k
 zlib-devel                x86_64  1.2.11-17.el8        centos-appstream   58 k
Upgrading:
[...]
 python3-dnf               noarch  4.7.0-7.el8          centos-appstream  545 k
 python3-dnf-plugins-core  noarch  4.0.21-10.el8        centos-appstream  230 k
 python3-hawkey            x86_64  0.63.0-7.el8         centos-appstream  116 k
 python3-libdnf            x86_64  0.63.0-7.el8         centos-appstream  778 k
 python3-librepo           x86_64  1.14.2-1.el8         centos-appstream   53 k
 sqlite-libs               x86_64  3.26.0-15.el8        centos-appstream  581 k
 yum                       noarch  4.7.0-7.el8          centos-appstream  201 k
Installing dependencies:
[...]
Installing weak dependencies:
 python3-unbound           x86_64  1.7.3-17.el8         centos-baseos     119 k

[...]

STEP 21: RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"     && python3 get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2548k  100 2548k    0     0  29.2M      0 --:--:-- --:--:-- --:--:-- 29.2M
ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
error: build error: error building at STEP "RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"     && python3 get-pip.py": error while running runtime: exit status 1
```

**Additional context**
The env variable about packages to install `INSTALL_PKGS` doesn't mention python directly. Python 3.6 seems to come as a dependency of `yum-utils` (`yum-utils noarch 4.0.21-10.el8` -> `python3-dnf noarch 4.7.0-7.el8` -> `python(abi) 3.6`)

**Comment by tbugfinder** [comment]
`ENV PYTHON_VERSION` is not used within Dockerfile.ubi8.
Master branch uses pip3.6.
- so the ENV PYTHON_VERSION line could be dropped
- changes applied to master should be merged into 4.x

@nichtraunzer

**Comment by tbugfinder** [comment]
@cschweikert Do we also have access to the build log file?

**Comment by tbugfinder** [comment]
I'm also wondering if those jenkins-agents in 4.x branch should pin to a 4.x tag of the base jenkins agent.

**Comment by tbugfinder** [comment]
OS - python36 matches current requirements.

The question about pinning is about pinning the definitions within ods-quickstarters branch 4.x.

All use latest instead of 4.x - latest is fine for me though.

https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/golang/docker/Dockerfile.ubi8#L1

https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/maven/docker/Dockerfile.ubi8#L1

https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/python/docker/Dockerfile.ubi8#L1


Available base image tags:
https://hub.docker.com/r/opendevstackorg/ods-jenkins-agent-base-ubi8/tags

**Comment by tbugfinder** [comment]
Github workflows do not care about BC overwrites, no?

https://github.com/opendevstack/ods-quickstarters/blob/4.x/.github/workflows/continuous-integration-workflow.yml#L151

**Comment by cschweikert** [comment]
Hi @tbugfinder, maybe there is a missunderstanding. When jenkins agents are build/updated on a cluster installation according to the manual (https://www.opendevstack.org/ods-documentation/opendevstack/4.x/jenkins/administration.html) they will do this by considering the overwrites from the BC. With this they will be build from the jenkins-agent-base image that lives on the respective ods namespace.
Regarding the github workflow you are right: It does not consider the `bc.yml` in the first place. AFAIK the github workflow is used for test puposes only.

To conclude: One one hand the github workflow will not have influence on the situation of an actual ODS instance. On the other hand by not using the right jenkins-agent-base image it is also not 100% comparable with the way it will be used. This leaves me thinking, if we are testing the right way here.

**Comment by tbugfinder** [comment]
It's well understood. I'm rather also on the path what we are testing here, though.

**Comment by metmajer** [comment]
@braisvq1996 is addressing this already

**Comment by tbugfinder** [comment]
the issue itself is solved.
