### ISSUE TITLE
terraform agent build failing

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#724]
**Describe the bug**
Due to recent changes/removals from centos repos terraform agent fails on building.

**To Reproduce**
1. Go to ['this github action run from 4.x'](https://github.com/opendevstack/ods-quickstarters/runs/5244440597?check_suite_focus=true)
2. See error

**Expected behavior**
Should build with success

**Screenshots**

**Affected version (please complete the following information):**
 - OpenShift: 4
 - OpenDevStack master

**Comment by gerardcl** [comment]
FYI @tbugfinder @nichtraunzer

**Comment by gerardcl** [comment]
@tbugfinder when you mentioned in the other PR that you need in the terraform agent "epel" you mean the centos8.repo as in https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/nodejs12/docker/yum.repos.d/centos8.repo ?

**Comment by tbugfinder** [comment]
I don't see "Extra Packages for Enterprise Linux 8" in the file centos8.repo.

With the switch to ubi8 repos terraform agent can use 
```
dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
```

**Comment by metmajer** [comment]
Can we please switch to UBI8 as soon as possible? Less security issues for all. Thanks
