### ISSUE TITLE
Nodejs 12 EOL in April

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#763]
**Is your feature request related to a problem?**
Nodejs version 12 reach EOL in April 2022 - [releases](https://nodejs.org/en/about/releases/)

**Describe the solution you'd like**
we should update to a newer version be it 14 or 16 (current LTS)

**Quickstarters with nodejs agent**
- typescript: @sino92
- cypress: @tbabik
- angular: @cschweikert
- ionic: @rianet @bljubisic

FYI - @metmajer @gerardcl @michaelsauter

**Comment by metmajer** [comment]
Agreed @braisvq1996. Could you list the affected Quickstarters and get in touch with the Quickstarter owners for their contributions?

According to https://github.com/opendevstack/ods-quickstarters/issues/694, quickstarters should support multiple runtimes to remain backwards compatible as much as possible.

**Comment by cschweikert** [comment]
I'd go for nodeJS 16. Actually there will be 18 (LTS) next month, but it might take some time until it is available in all the different package managers.
Also we are already using a custom agent that uses nodeJS 16 and it doesn't seem to cause any issues. On our end It works together with different versions of cypress, at least Angular 11 and 13 and also latest Express server.

Following things to think about:
1. Which branches should get the new agent? `3.x`, `4.x` and `master`?
2. Do we keep the old nodeJS 12 version in parallel in one or more branches?
3. Do we update everything (agent + quickstarters) with a single blow or do we go step-by-step?

I created a first branch already that shows, how a full replacement from nodeJS 12 to nodeJS 16 might look like:
https://github.com/opendevstack/ods-quickstarters/commit/306abe920cadafec4d3e134bfca4af6fb25fcc09
I haven't tested anything of this yet.

**Comment by braisvq1996** [comment]
>Which branches should get the new agent? 3.x, 4.x and master?

3.x will not be needed to be updated, only 4.x and master.

> Do we keep the old nodeJS 12 version in parallel in one or more branches?

We should keep nodejs 12 at least in 4.x and add in parallel nodejs 16, not sure for master @metmajer 

> Do we update everything (agent + quickstarters) with a single blow or do we go step-by-step?

We have 4 Quickstarters that make use of nodejs, lets go step by step

**Comment by cschweikert** [comment]
How about we do the following steps:
1. on `master` replace 12 with 16 all over the place and make all nodeJS-based quickstarters working properly again
2. backport nodeJS 16 agent from `master` to `4.x` for offering it in parallel with 12 (also needs special documentation and build/test scripts to work with both versions in parallel)
3. backport the adjustments made on the quickstarters from `master` to `4.x`

The first point might look like shown in this PR: https://github.com/opendevstack/ods-quickstarters/pull/764

**Comment by metmajer** [comment]
@cschweikert I am just trying to be practical. EOL does not mean that existing nodeJS applications will not run anymore. Some users of this Quickstarters might be willing to accept running on an EOL version, or simply cannot afford unknown risks that might come with an upgrade to a later version. If, however, users need to rebuild their Agents, because of a SonarQube update, they would still be safe. I am not saying we should advertise NodeJS 12 anymore, so the QS should definitely be a 16.

**Comment by cschweikert** [comment]
@metmajer For `4.x` I'm totally with you. How about `master`?

As long as nobody deletes the cluster-local `4.x` branch, rebuilding old agents should be possible. Or am I missing something?

**Comment by metmajer** [comment]
@cschweikert I consider this valuable in all branches since some distributors (vendors) might provide their solutions requesting a particular version, not necessarily the latest LTS.

**Comment by tbugfinder** [comment]
Several weeks from now, security tooling might raise alerts - and  then? Platform offerings are insecure by default? So the message isn't really beneficial (my 2ct).

**Comment by metmajer** [comment]
@tbugfinder what exactly are you referring to? Christian's proposal to re-use old Agents or something else?

**Comment by tbugfinder** [comment]
I was referring to the "message" of still supporting EOL nodejs12. This feels contrary to any effort and arguments regarding security. EOL means EOL, so dropping nodejs12 at least of main (master) is needed.

**Comment by metmajer** [comment]
Fine with me if you will migrate all existing nodejs12 apps of our colleagues manually to 16 :) Otherwise, let's keep 16 in there and we do a proper sunsetting before we remove it.

**Comment by cschweikert** [comment]
I had problems with NodeJS 14+ and the `fe-angular` QS. See also https://github.com/opendevstack/ods-quickstarters/issues/662
I started updating `fe-angular` in parallel. See also https://github.com/opendevstack/ods-quickstarters/issues/765

**Comment by metmajer** [comment]
@cschweikert @tbugfinder I would be supportive for a QS that contains only NodeJS 16 if there is absolutely no risk for existing applications based on NodeJS 12. Certainly, as a Platform provider, I do not want to take this risk on me. If we cannot guarantee backwards-compatibility for existing applications, we should offer this backwards compatibility as a general principle of a QS and use awareness and education (and security monitoring solutions) to drive teams to use a more modern version. However, we cannot simply stop continuity of service at a technical level.

**Comment by braisvq1996** [comment]
I am also in favor of @metmajer opinion, we must support older versions.
Nodejs 12 will reach EOL soon but we should support it for some time and encourage users to update (I expect to not have this kind of situation in the futute, supporting a EOL version).
The moment we decide to drop a certain version of a builder image we need to have enough time (months) for the users to update.

**Comment by tbugfinder** [comment]
Is there a doc section or Code section to inform users about deprecated technology? Maybe consider adding this information already for nodejs16 agent, so that by „platform release“ before or after nodejs16 EOL date this agent version will be deprecated and then removed?

**Comment by cschweikert** [comment]
@tbugfinder regarding EOL: I added some lines to the documentation `ods-quickstarters/docs/modules/jenkins-agents/pages/...`:
* v12: https://github.com/opendevstack/ods-quickstarters/commit/031adcb51ab4320f0237149cf7dce81789de6986#diff-13808194cbf94924fe90ad002dcf8e6d4effe11a5ca2a1270d34f59676482619R9
* v16: https://github.com/opendevstack/ods-quickstarters/commit/031adcb51ab4320f0237149cf7dce81789de6986#diff-f835ac73372775c0c68cc21c984b761d2a75aeddc448888a1b1fc5a4ccd05734R9

**Comment by tbugfinder** [comment]
👍

**Comment by filex** [comment]
When will the `jenkins-agent-nodejs16` image be available for existing ODS projects? I see that the issue is closed and merges have been made. But I don't see the expected image in the OpenDevStack's Image Streams at inh-ocdev (EU).

**Comment by braisvq1996** [comment]
> When will the `jenkins-agent-nodejs16` image be available for existing ODS projects? I see that the issue is closed and merges have been made. But I don't see the expected image in the OpenDevStack's Image Streams.

Hi @filex , we will make the update in the following changes, once we do so it will be announced in the public company channels
