### ISSUE TITLE
DS-Dash Quickstarter

### ISSUE THREAD

**Issue by drdivine** [opendevstack/ods-quickstarters#77]
**Describe the solution you'd like**
As a data scientist, I would like to rapidly prototype solutions and engage stakeholders as quickly as possible, utilizing a dash board created using plotly dash. This will allow the FE Engineers to focus on CSS ;)

**Comment by gerardcl** [comment]
@drdivine we will need to add a nice documentation readme-like, see how it is done in the other quckstarters

**Comment by michaelsauter** [comment]
This is cool, but we probably need more heads-up with things like this before they can make it into a release.

I propose to move this out of ODS 2. We could make a separate repo, e.g. `lab-quickstarters`, where things like this go until they have matured and we do see some examples how it is used.

**Comment by gerardcl** [comment]
@michaelsauter I see your point, but just to put some info: this is already something that is going to be used since it enables Data Scientists to faster prototype and test with users in a more real-like environment. I agree though to keep it not yet under ODS2 since it is really short notice and since anyway the quickstarter can be deployed once ODS2 is in place, wherever it is located.

**Comment by sklingel** [comment]
I would like to push this topic, again. We need an python alternative to the rshiny quickstarter. Rather soon then latern? How do we push this?

**Comment by michaelsauter** [comment]
@sklingel Definitely go ahead with this. I would propose to:

1. Create this quickstarter in our internal bitbucket, and have it be used a couple of times by users to collect feedback
2. This ensures that there is a need for it and how we solve it is the right way
3. When the solution works reliably, and we have a few people who own / maintain the quickstarter, we can promote it to an "official" quickstarter

Does that sound good to you? Let me know when you need help to create the quickstarter internally.

**Comment by drdivine** [comment]
This is a good idea 💡!

________________________________

**Comment by gerardcl** [comment]
@drdivine can we close this issue since there is not too much push for this anymore? looks like the approach for internal quickstarters is working so far also.
