### ISSUE TITLE
inf-terraform-aws: self-check feature

### ISSUE THREAD

**Issue by nichtraunzer** [opendevstack/ods-quickstarters#784]
Since setup of the inf-terraform-aws quickstarter requires multiple configuration steps it might be helpful having a function available which does some checks on the existing configuration files to verify proper settings (syntax).
e.g.
```
$ make config-check
**** Checking environments configuration ****
checking dev.yml  ✔️ 
checking test.yml  ✔️ 
checking prod.yml  ⛔  Account not configured
**** Checking backend configuration ****
checking backend.tf  ⛔ Store not configured
...
$
```
This could also executed during the pipeline run and mark it as unstable in case of a missing configuration. Running in the pipeline would allow more advanced checks like
- check access rights to state file location
- check secrets configuration in OC

**Comment by tbugfinder** [comment]
Basically a dry-run :-) without terraform apply/destroy cycles?

**Comment by renedupont** [comment]
@nichtraunzer as discussed recently, to be more IDE independent (devconfig.json requires VS Code), an alternative way of using terrarium could be to add a make target to the Makefile here that basically starts the docker container and mounts the path. e.g.:
`docker run -it -v $(pwd):/workspace/terrarium ghcr.io/nichtraunzer/terrarium sh`
maybe even check in that target if the container is already running.

**Comment by renedupont** [comment]
Another thing we discussed was replacing the git pre commit hooks by `make` targets as well. This would reduce complexity and prevents the issue of needing to run `make prep-test` several times for each file

**Comment by nichtraunzer** [comment]
Adding new targets to Makefile:
make clean:
- removes unnecessary files from working directory 
- has no output 
make check-config:
- does some basic checks on configuration files and account settings
- output:
```
Account "XXXXXXXXXXXX" is configured for the "dev" environment...........Passed
There is no account configured for the "test" environment................ Warn 
There is no account configured for the "prod" environment................ Warn 
AWS Account configured using SSO.........................................Passed
  Using "XXXXXXXXXXXX:blah@blub.com".................  ..................Passed
Backend configured to "TFStateLocation"..................................Passed
  Check Account can write to bucket......................................Passed
```
see PR [#850](https://github.com/opendevstack/ods-quickstarters/pull/850)
