### ISSUE TITLE
Jcenter repository not available and build step fails

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#804]
**Describe the bug**
Currently Jcenter seems not available and have made the pipelines fails due to a package that was not stored properly in Nexus.
In the Java/SpringBoot QS we have this repository ([here](https://github.com/opendevstack/ods-quickstarters/blob/master/be-java-springboot/templates/gradle-repositories.template#L11)) and maven public below.
Maven public is a group type repository in Nexus and already contains[ jcenter and maven-central](https://github.com/opendevstack/ods-core/blob/master/nexus/json/createRepos.json#L24-L26) (that points to https://repo1.maven.org/maven2/) so it does not makes sense to have both in gradle

@renedupont

**Comment by renedupont** [comment]
In that case I think we can remove [this](https://github.com/opendevstack/ods-core/blob/master/nexus/json/createRepos.json#L10) from the nexus repos?

**Comment by braisvq1996** [comment]
yeah, we could remove it from Nexus and for the Quickstarters
At the end, we have maven-central for this kind of packages

**Comment by victorpablosceruelo** [comment]
This is needed right now. Quickstarters cannot compile because jcenter dependencies cannot be found.

https://github.com/opendevstack/ods-quickstarters/pull/807/commits/6ae942407bdc53c752325fc057271b6ad6f2407a

Thanks for pointing it out, Brais.

**Comment by victorpablosceruelo** [comment]
More info about this:
https://stackoverflow.com/questions/66651640/jcenter-deprecation-impact-on-gradle-and-android#:~:text=Summary%3A%20After%20February%201%2C%202022%20the%20jcenter%20%28%29,will%20be%20removed%20in%20the%20next%20major%20release.

**Comment by victorpablosceruelo** [comment]
Provisioning app is affected by this too:
https://github.com/opendevstack/ods-provisioning-app/issues/737
