### ISSUE TITLE
Maven agent not able to switch to Java 17

### ISSUE THREAD

**Issue by renedupont** [opendevstack/ods-quickstarters#828]
**Describe the bug**

Using Java 17 (ODS 4.x) [as described in the docs](https://www.opendevstack.org/ods-documentation/opendevstack/4.x/quickstarters/be-java-springboot.html#_migration_to_java_17) does not work. There are actually two issues, one is a bug in the jenkins-maven-agent that lets the stage fail because it cannot find the use-java17 script and the second is that our sonar version seems to not yet work with Java17, so that stage fails as well. 
 
The (workaround) solution is to first switch to the correct folder of the scripts (issue 1) before the gradle build and after the build switch back to Java 11 for the sonar stage to succeed (issue 2).
 
E.g. like this:
```
sh(script: "cd /home/jenkins/ && ./use-j17.sh", label: 'switch to Java 17')
def status = sh(script: "./gradlew clean build --stacktrace --no-daemon", returnStatus: true)
sh(script: "cd /home/jenkins/ && ./use-j11.sh", label: 'switch back to Java 11 for sonarqube stage')
```
 
Would be nice if we could fix this in the maven-agent (and quickstarter?) so that we don't need to use this workaround.

@stitakis I'll be out for a while otherwise I would have looked into it myself but still wanted to have this issue noted down.

**Comment by braisvq1996** [comment]
@renedupont @stitakis it seems that SonarQube does not support java 16 and 17 even in the current LTS version (8.9) and we currently use version 8.2-> https://community.sonarsource.com/t/will-java-16-and-17-be-supported-in-sonarqube-8-9-lts/47535

**Comment by renedupont** [comment]
Yes, therefore I'd suggest to keep that workaround of switching back to java 11 after the gradle build in the readme/docs regarding using java 17 as long as sonarqube does not support it. I fear once this happens we have to do the same with the next java LTS (java 23) version 🤣.

**Comment by braisvq1996** [comment]
I was checking yesterday about this topic and it is very likely that we will face something similar for next java LTS from some coments I read.....
Acording to SonarQube if we want to be able to get support for java 16 and 17 we should use SonarQube 9.x (in reality 9.3 or above)

**Comment by renedupont** [comment]
I guess this was fixed by now with this line: https://github.com/opendevstack/ods-quickstarters/blob/4.x/be-java-springboot/Jenkinsfile.template#L29
I close this @braisvq1996
