### ISSUE TITLE
Terraform UBI agent fails to build with latest base image

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#847]
**Describe the bug**
Terraform build with Dockerfile.ubi8 fails to build due to the latest changes in Jenkins base agent

**To Reproduce**
1. Build Terraform with Dockerfile.ubi8
2. See error

**Expected behavior**
The agent should build successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/26645694/190361004-df9b712b-2bcd-4b37-b21f-c235683a1c9c.png)

**Affected version:**
 - OpenDevStack: master and 4.x

**Log Output**
```
Step 45/47 : RUN ls $JAVA_HOME/lib/security/cacerts     && chown 1001:0 $JAVA_HOME/lib/security/cacerts     && chmod g+w $JAVA_HOME/lib/security/cacerts
 ---> Running in 8e6914fc3ede
ls: cannot access '/lib/security/cacerts': No such file or directory
The command '/bin/bash -o pipefail -c ls $JAVA_HOME/lib/security/cacerts     && chown 1001:0 $JAVA_HOME/lib/security/cacerts     && chmod g+w $JAVA_HOME/lib/security/cacerts' returned a non-zero code: 2

Error: Process completed with exit code 2.
```

**Additional context**
This is due to JAVA_HOME being removed in base image
Related to https://github.com/opendevstack/ods-core/pull/1181

@victorpablosceruelo

**Comment by nichtraunzer** [comment]
will fix it !
