### ISSUE TITLE
oauth-proxy sidecar image update

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#862]
**Describe the bug**
Current ODS quickstarters that make use of the openshift oauth-proxy sidecar container are working with the image `openshift/oauth-proxy:latest` (check it [here](https://github.com/opendevstack/ods-quickstarters/blob/e0b14bed2d4ef50850f9bf0930a319df0dd38230/common/ocp-config/ds-component-environment/ds-component-oauthproxy.yml#L131)), and that is no longer working as expected.

RedHat catalogue provides image `registry.redhat.io/openshift4/ose-oauth-proxy:latest`, which is the right/maintained one (see [catalogue](https://catalog.redhat.com/software/containers/openshift4/ose-oauth-proxy/5cdb2133bed8bd5717d5ae64?container-tabs=overview))

**To Reproduce**
1. Provision jupyter or r-shiny
2. When running on new OCP4 clusters it does not work

**Expected behavior**
The OpenShift OAuth Proxy shall work.

**Affected version (please complete the following information):**
 - OpenShift: >3.9
 - OpenDevStack: 4, master

**Comment by gerardcl** [comment]
This might break the RM since the image is not owned by ODS nor in the `openshift` namespace. The solution might be required to be managed via PaaS team (which implies defining a life cycle for this image and get `latest` regularly).

FYI @braisvq1996 @metmajer

**Comment by braisvq1996** [comment]
I have asked PaaS team if this is possible, I will let you know

**Comment by gerardcl** [comment]
ok, thanks from the tests from @braisvq1996 we confirm we require the image to be in the cluster, hence the PRs will change in a more "cluster management" docs way.

basically, we need a cluster admin from now on to make sure (when installing an ODS in a cluster) to run:

```
oc -n openshift tag registry.redhat.io/openshift4/ose-oauth-proxy:latest ose-oauth-proxy:latest --scheduled
```

and, to reference that in the deployments as:

```
          kind: ImageStreamTag
          name: 'ose-oauth-proxy:latest'
          namespace: openshift
```

**Comment by gerardcl** [comment]
@braisvq1996 and me plan to test adding the sidecar image in the foo-cd namespace at provisioning time, will come back with results next week

**Comment by braisvq1996** [comment]
We can take the same approach as mono-repo Quickstarter. Having 1 pod with 2 containers

- We will aling Data-Science Quickstarters to use sidecar containers. 
- Create a BC resoures for the Oauth component in order to build it in each project (as if we just pull it from registry in case the image has any issue or vulnerability we cannot make any change as it comes directly from any vendor)  and support release process.
