### ISSUE TITLE
Maintenance of Golang agent and quickstarter

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#877]
We are starting to implement a maintenance policy for ods components and will be checking versions of packages and components.

**Golang Agent**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| GO_DISTRIBUTION_URL  | 1.14.2  | 1.20.2 (latest) | [bc.yml](https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/golang/ocp-config/bc.yml#L19-L20) |
| Golang-cli  | v1.25.0  | v1.52.2(latest) | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/golang/docker/Dockerfile.ubi8#L20) |

The go version in the agent is out of support already -> https://go.dev/doc/devel/release

**Golang Quickstarter**
The quickstarter uses latest tag for alpine dockerhub image so no need to udpate it

@michaelsauter @henrjk

**Comment by braisvq1996** [comment]
In the case we update the Go version, old quickstarters that have already been deployed will be able to continue building their go application ?

**Comment by michaelsauter** [comment]
> In the case we update the Go version, old quickstarters that have already been deployed will be able to continue building their go application ?

Yes! Go is probably the language out of the ones used in the quickstarters with the best guarantees around that. See https://go.dev/doc/go1compat.
