### ISSUE TITLE
Maintenance of Maven agent, Java and Spock-Geb quickstarter

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#878]
We are starting to implement a maintenance policy for ods components and will be checking versions of packages and components.

**Maven Agent**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| Maven  | 3.5.4  | 3.8.8 | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/maven/docker/Dockerfile.ubi8#L45) |
| Gradle  | gradle-7.3-bin  | gradle-7.6.1-bin | [gradle-wrapper.properties](https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/maven/docker/gradle/wrapper/gradle-wrapper.properties#L3) |

**Java-SpringBoot Quickstarter**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| jdk base image | ubi8/openjdk-17  | ubi9/openjdk-17 | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/be-java-springboot/files/docker/Dockerfile#L1) |
| Gradle  | gradle-7.3-bin  | gradle-7.6.1-bin | [gradle-wrapper.properties](https://github.com/opendevstack/ods-quickstarters/blob/master/be-java-springboot/files/gradle/wrapper/gradle-wrapper.properties#L3) |
| SpringBoot  | 2.7.1  | 2.7.10 | [Jenkinsfile](https://github.com/opendevstack/ods-quickstarters/blob/master/be-java-springboot/Jenkinsfile#L23) |

Should we update SpringBoot version to 3.x version ?

**Spock-Geb Quickstarter**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| Gradle  | gradle-7.4-bin  | gradle-7.6.1-bin | [gradle-wrapper.properties](https://github.com/opendevstack/ods-quickstarters/blob/master/be-java-springboot/files/gradle/wrapper/gradle-wrapper.properties#L3) |
| spockVersion | 2.1-groovy-3.0  | 2.2-groovy-3.0 or 2.3-groovy-3.0 | [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |
| Junit  | 5.8.2  | 5.9.2 | [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |
| Geb  | 5.1  | 6.0 or 7.0 | [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |
| Selenium | 4.1.2  | 4.8.3 (latest) | [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |
| htmlunit  | 3.58.0  | 4.8.1 (latest) | [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |
| unirest  | 3.13.6  | 3.13.13 or 3.14.2 (latest) | [build.gradle](https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-spock-geb/files/build.gradle#L52-L57) |

To update Geb to version 7.0 we also need to update spockVersion to 2.3-groovy-3.0

@stitakis @renedupont

**Comment by renedupont** [comment]
I think for the quickstarters it is not an issue to update since a user would just get the latest versions while provisioning without any ties to existing applications. Regarding the maven agent I would think so too, but I'm not 100% sure, AFAIK both maven and gradle also remove stuff once in a while throughout versions, but that might only be true for major versions.

**Comment by braisvq1996** [comment]
Thanks for taking a look @renedupont.
With that approach users would need to modify their springboot and geb quickstarters that they already have in order to download maven or gradle when building right ?

(Gradle is already being downloaded as you said when building)
![image](https://user-images.githubusercontent.com/26645694/229080746-5fd58873-8965-4fe3-829e-a8f2a8c038ee.png)

**Comment by renedupont** [comment]
Yes and no. The thing is that currently, if someone has specified the exact version of gradle in the gradle wrapper properties that is also installed in the image, then it does not need to download the distro during the pipeline. But that is highly unlikely to happen. That means for gradle I don't see any change for them to do.
AFAIK maven is not used for any quickstarter, so a user who wants to use maven would have had to exchange gradle with maven in their provisioned project manually. If they did this and are actually using maven, they could continue to use the (by then deprecated) maven agent until they are also using the maven wrapper in their project (what they most likely hopefully already do) and then switch to the java agent.
