### ISSUE TITLE
Maintenance of Scala agent and quickstarter

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#879]
We are starting to implement a maintenance policy for ods components and will be checking versions of packages and components.

**Scala Agent**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| Sbt  | 1.5.4  | 1.8.2 | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/scala/docker/Dockerfile.ubi8#L23) |
| Java  | 11  | 11 or 17 | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/scala/docker/Dockerfile.ubi8#L10) |

Should we use the same java verison as the one used in Scala Quickstarter ?

**Scala Quickstarter**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| Java base image | adoptopenjdk/openjdk8:ubi-minimal-jre  | adoptopenjdk/openjdk11:ubi-minimal-jre | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/be-java-springboot/files/docker/Dockerfile#L1) |
| Sbt  | 1.3.7  | 1.8.2 | [build.properties](https://github.com/opendevstack/ods-quickstarters/blob/master/be-scala-play/be-scala-play.g8/project/build.properties) |
| Scala  | 2.13.2  | 2.13.10 | [build.sbt](https://github.com/opendevstack/ods-quickstarters/blob/master/be-scala-play/be-scala-play.g8/src/main/g8/build.sbt#L10) |

Should we update Scala to version 3.x ?

@oalyman

**Comment by braisvq1996** [comment]
In the case we update the Sbt version, old quickstarters that have already been deployed will be able to continue building their application ?

**Comment by oalyman** [comment]
For the Scala Jenkins agent I will:
- update Sbt to 1.8.2
- use the most recent Java Version of Java 11
  Currently the Playframework does not right out of the box completely work with Java 11.
  And this is currently the only existing Quickstarter for Scala.
  As soon as this changes we can update to Java 17 (it most likely will habben with playframework 2.9)

For the `be-scala-play` quickstarter
- update Sbt to 1.8.2
- update to the most recent scala 2.13 version.
  The Playframework does not support Scala 3 yet.

> In the case we update the Sbt version, old quickstarters that have already been deployed will be able to continue building their application ?

In theory yes. They should continue working as the sbt version to use will be based on the definition of the `build.properties` of the concrete project.
So in case in your existing project `build.properties` you defined `sbt.version=1.3.7` it should continue building with that version.
I will test it with an existing project provisioned based on the current version.
