### ISSUE TITLE
Update Typescript Version in 'be-typescript-express' & 'fe-ionic'

### ISSUE THREAD

**Issue by akhilsoman** [opendevstack/ods-quickstarters#88]
**Describe the bug**
'be-typescript-express' & 'fe-ionic' quickstarters are using an older version of typescript. At the moment the build works fine except SonarQube fails during scanning because of the unsupported version.

**To Reproduce**
Steps to reproduce the behaviour:
1. Provision a be-typescript-express' or 'fe-ionic' quickstarter 
2. Check the Jenkins log of the deployment job, you could see the SonarQube error.

**Expected behavior**
SonarQube Analysis should run for both quick starters

**Screenshots**

**Affected version (please complete the following information):**
 - 2.x and earlier versions 

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
INFO: Load project repositories (done) | time=8ms
ERROR: You are using version of TypeScript 2.9.2 which is not supported; supported versions >=3.2.1
ERROR: If it's not possible to upgrade version of TypeScript used by the project, consider installing supported TypeScript version just for the time of analysis
ERROR: Failure during analysis, Node.js command to start eslint-bridge was: {NODE_PATH=/tmp/workspace/..../docker/dist/node_modules} node /tmp/workspace/..../.scannerwork/.sonartmp/eslint-bridge-bundle/package/bin/server 43536
java.lang.IllegalStateException: Unsupported TypeScript version
	at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.processParsingError(AbstractEslintSensor.java:149)
	at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.processResponse(AbstractEslintSensor.java:188)
	at org.sonar.plugins.javascript.eslint.TypeScriptSensor.analyze(TypeScriptSensor.java:154)
	at org.sonar.plugins.javascript.eslint.TypeScriptSensor.analyzeFilesWithTsConfig(TypeScriptSensor.java:141)
```

**Additional context**
For fe-ionic this could be clubbed with #21

**Comment by velcrin** [comment]
We looked into the `be-typescript-express` quickstarter and it looks like it using yeoman with a very old [generator](https://github.com/opitzconsulting/generator-node-express-typescript). We might want to move away from yeoman and use npx instead. There is an official [generator](https://expressjs.com/en/starter/generator.html) that does not use typescript but at least it is official and maintained. If one needs typescript, he could setup it up himself :-)

**Comment by bljubisic** [comment]
Ionic quickstarter has been updated in separate issue, so it is now at version 5, with Angular version 8 there.

**Comment by michaelsauter** [comment]
Closing this. Typescript version is tracked in #95.
