### ISSUE TITLE
Maintenance of Gateway-Nginx quickstarter

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#880]
We are starting to implement a maintenance policy for ods components and will be checking versions of packages and components.

**Gateway-Nginx Quickstarter**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| openresty base image | 1.19.3.2-fedora-rpm  | 1.19.9.1-14-fedora-rpm | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/be-gateway-nginx/files/docker/Dockerfile#L2) |

Should we update the base image to 1.21.x (1.21.4.1-4-fedora-rpm) instead ?

@gerardcl

**Comment by gerardcl** [comment]
okidoki! I will switch to rocky since it is also supporting arm64/v8 platforms (aka M1,...) ok? so far it is "the same" to fedore 👍
