### ISSUE TITLE
Maintenance of Terraform agent, AWS and Azure quickstarters

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#881]
We are starting to implement a maintenance policy for ods components and will be checking versions of packages and components.

**Terraform Agent**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| Nodejs  | 16.17.1  | 18.x | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/terraform/docker/Dockerfile.ubi8#L22) |
| Terraform  | 1.2.9  | 1.3.7 | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/terraform/docker/Dockerfile.ubi8#L15) |
| Ruby  | 2.7.5  |2.7.7 | [Dockerfile](https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-agents/terraform/docker/Dockerfile.ubi8#L18) |

**AWS Quickstarter**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| Terraform  | 1.2.9  | 1.3.7 | [.terraform-version](https://github.com/opendevstack/ods-quickstarters/blob/master/inf-terraform-aws/files/.terraform-version) |
| Ruby  | 2.7.5  |2.7.7 | [.ruby-version](https://github.com/opendevstack/ods-quickstarters/blob/master/inf-terraform-aws/files/.ruby-version) |

**Azure Quickstarter**

| Package | Current Version | Sugested version | Location |
| ------------- | ------------- | ------------- | ------------- |
| Terraform  | 1.2.9  | 1.3.7 | [.terraform-version](https://github.com/opendevstack/ods-quickstarters/blob/master/inf-terraform-azure/files/.terraform-version) |
| Ruby  | 2.7.5  |2.7.7 | [.ruby-version](https://github.com/opendevstack/ods-quickstarters/blob/master/inf-terraform-azure/files/.ruby-version) |

Should the Ruby be updated to 3.x version (3.2) in the agent and quickstarters?

@nichtraunzer  @tbugfinder

**Comment by tbugfinder** [comment]
Are we focussing on 4.x or 5.x ?

**Comment by tbugfinder** [comment]
How often do we apply this maintenance cycle?

**Comment by braisvq1996** [comment]
> Are we focussing on 4.x or 5.x ?

This is maintenance for 4.x branch, but from now on we only need to prepare PRs for master branch and when a release/update is planed we will merge back to release branch (4.x or in the future 5.x)

> How often do we apply this maintenance cycle?

The initial idea is to apply it once per 2 months, but this may change as this are the firsts iterations.

**Comment by braisvq1996** [comment]
Take into account that this issue does not mean that we must update, it is just to open a discussion about it and see if it is worth it

**Comment by braisvq1996** [comment]
@tbugfinder @nichtraunzer , if you think it is not necesary to update at this moment we open this topic agein the next Maintenance check.

**Comment by tbugfinder** [comment]
Right now, we'd like to skip the proposed version bumps.
Nevertheless especially Ruby3.x will be planned but this takes more time.

**Comment by braisvq1996** [comment]
Hi @tbugfinder , next iteration of the maintenance is here

Something I found in a recent build is that current version of ruby will reach EOL soon

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/26645694/228237320-63f2a4d6-fd41-4da5-890d-fe1c839c888b.png)

**Comment by nichtraunzer** [comment]
Thanks @braisvq1996 - we have that on the radar.

**Comment by tbugfinder** [comment]
Ruby 3.x upgrade requires also (major) upgrades to cinc-auditor and kitchen-terraform.
Version 7.0.0 of kitchen-terraform is not yet released but in development.

Question again: is target 4.x or 5.x?
Do we expect an identical agent image tag or a distinct one so that active projects can migrate step-by-step?

**Comment by braisvq1996** [comment]
As far as i know, we still expect to use 4.x version

**Comment by nichtraunzer** [comment]
created a separate issue for the Ruby 3 topic https://github.com/opendevstack/ods-quickstarters/issues/914
