### ISSUE TITLE
(E2E) Test Quickstarter with Spock/Geb/Unirest for Java and Groovy

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-quickstarters#89]
**Is your feature request related to a problem? Please describe.**
Once all code-related and service-related components have been deployed (using the release manager), I want to be able to run automated tests against any combination of live components (integration, acceptance and system-level tests).

**Describe the solution you'd like**
The quickstarter-embedded framework shall support writing tests using [Spock](http://spockframework.org), [Geb](https://gebish.org) and [Unirest](http://unirest.io), and provide a test structure for integration and acceptance testing for both Java and Groovy.

**Additional context**
Following the existing pattern, we would call this one *e2e-spock-geb*. As a side note, I find the *e2e* misleading as this name is closest to system-level than acceptance or integration testing. @michaelsauter let me know if you think we should reconsider this prefix.

**Comment by michaelsauter** [comment]
@metmajer How would this relate / differ from the e2e-cypress one? Just different tech or something else?

**Comment by metmajer** [comment]
Exactly, it's a different tech stack.

**Comment by metmajer** [comment]
@hrcornejo FYI
