### ISSUE TITLE
Missing Documentation on Release Manager Quickstarter

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-quickstarters#9]
**Describe the bug**
ODS 1.2 introduced a [release manager quickstarter](https://github.com/opendevstack/ods-project-quickstarters/blob/master/rundeck-jobs/quickstarts/release-manager.yaml).
The Release Manager (purpose, how to use it etc, is not documented)

**Expected behavior**
The release manager quickstarter / and release manager should be documented as a quickstarter in the [documentation](https://github.com/opendevstack/ods-project-quickstarters/tree/master/docs/modules/ROOT/pages)

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 1.2

**Comment by metmajer** [comment]
Thanks for pointing this out @rattermeyer!
