### ISSUE TITLE
Allow configuring quotas to the worker pod

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-quickstarters#90]
The Airflow OpenShift Executor should be able to assign resource quotas to the worker pod during the task execution based on airflow.cfg and/or environment variables

**Comment by michaelsauter** [comment]
`shared-images` is no more, so moving this to quickstarters now.

**Comment by gerardcl** [comment]
closing this issue since it was solved in the past ODS 2 release by having an airflow agent and making the whole dependencies binded to an ODS project level (not anymore in shared-images) --> #60
