### ISSUE TITLE
Python agent with version 3.11

### ISSUE THREAD

**Issue by p-goodman** [opendevstack/ods-quickstarters#902]
**Is your feature request related to a problem? Please describe.**
We are developing software which we would like to upgrade to the maximum possible Python version. In order to run tests on the CI agents, we need a preinstalled Python 3.10 or 3.11.

**Describe the solution you'd like**
Preinstall Python 3.10 and 3.11 on the python agent

**Describe alternatives you've considered**
We might write our own agent based on the base agent but this would take some time

**Additional context**
none

**Comment by braisvq1996** [comment]
Hi @p-goodman,
The current approach is to install python with yum modules and I do not think there is one for version 3.10 or 3.11
@gerardcl

**Comment by gerardcl** [comment]
Hi @p-goodman,

The agreement so far is to support RedHat UBI images, as well as to support official RedHat software packages so, since there is no official RedHat UBI images for python versions above 3.9 yet (see https://catalog.redhat.com/software/containers/search?q=python3&p=1) to run the build applications, we can't provide it yet.

What is the requirement to go for 3.10 or 3.11?

Best,

**Comment by p-goodman** [comment]
Hi @braisvq1996 and @gerardcl ,
thanks for your answers.

There's no strict requirement but we would like to build modern state-of-the-art software. We are upgrading all our applications from 3.8 (because this has EOL next year) and would like to make the biggest version jump possible. 3.9 is also quite old as it was released in 2020 and has EOL in 2025. But I guess we can live with that or we might consider to build our own agent.

Thanks nevertheless. Kind regards
Philipp

**Comment by braisvq1996** [comment]
> Hi @p-goodman,
> 
> The agreement so far is to support RedHat UBI images, as well as to support official RedHat software packages so, since there is no official RedHat UBI images for python versions above 3.9 yet (see https://catalog.redhat.com/software/containers/search?q=python3&p=1) to run the build applications, we can't provide it yet.
> 
> What is the requirement to go for 3.10 or 3.11?
> 
> Best,

It seems that a few days ago Red Hat provides Python 3.11 images and packages (but not 3.10 though )
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_installing-and-using-python_configuring-basic-system-settings
- https://catalog.redhat.com/software/containers/search?q=python3&p=1
