### ISSUE TITLE
TypeScript quickstarter defines no TypeScript version

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-quickstarters#95]
**Describe the bug**
A quickstarter should bind a technology to a specific version and be transparent about it. The quickstarter installs TypeScript via a Yeoman generator in the `Jenkinsfile`, see [here](https://github.com/opendevstack/ods-quickstarters/blob/master/be-typescript-express/Jenkinsfile#L44). This generator, via https://www.npmjs.com/package/generator-node-express-typescript, however, does not mention the Typescript version used.

**Expected behavior**
A version shall be made explicit.

**Comment by metmajer** [comment]
@rattermeyer a reminder to pin the version of TypeScript in your quickstarter. Thanks!

**Comment by michaelsauter** [comment]
@sino92 Assigning to you since you expressed you want to look after it for the 3.0 cycle.

**Comment by michaelsauter** [comment]
Please make sure to update to the latest version if possible.

**Comment by sino92** [comment]
Revisiting a more fundamental question about the quickstarter first: https://github.com/opendevstack/ods-quickstarters/issues/315

**Comment by sino92** [comment]
With the latest remaking of Typescript quickstarter, we have clarity on the used lib versions here in [Jenkinsfile](https://github.com/opendevstack/ods-quickstarters/blob/master/be-typescript-express/Jenkinsfile#L17) and in [ODS documentation](https://github.com/opendevstack/ods-quickstarters/blob/master/docs/modules/quickstarters/pages/be-typescript-express.adoc).
Closing this issue now.
