### ISSUE TITLE
ds-rhiny: use helm during/for provisioning of resources

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-quickstarters#964]
Currently the ds-rshiny quickstarter provisioning executes a script during quickstarter deployment for setting up required resources.
Maintenance of the deployed quickstarter would be simpler if the resources get deployed "in-code" and are available within the git repository.

https://github.com/opendevstack/ods-quickstarters/blob/293b2abbf88750130bbf80a3a7cc3c27980a9719/ds-rshiny/Jenkinsfile#L23-L28

**Comment by gerardcl** [comment]
closing - superseded #1013
